infix using "C:\COUNTRIES\UG7I\UGHR7IFL.dct"

label variable hhid     "Case Identification"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number (answering Household questionnaire)"
label variable hv004    "Ultimate area unit"
label variable hv005    "Household sample weight (6 decimals)"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv008a   "Date of interview Century Day Code (CDC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in household"
label variable hv011    "NA - Number of eligible men in household"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under (de jure)"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "NA - Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample strata for sampling errors"
label variable hv023    "Stratification used in sample design"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "NA - Place of residence"
label variable hv027    "Household selected for male interview"
label variable hv028    "Household weight for male subsample (6 decimals)"
label variable hv030    "Field supervisor"
label variable hv031    "NA - Field editor"
label variable hv032    "NA - Office editor"
label variable hv035    "Number of eligible children for height and weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Household selected for hemoglobin"
label variable hv045a   "Language of questionnaire"
label variable hv045b   "Language of interview"
label variable hv045c   "Native language of respondent"
label variable hv046    "Translator used"
label variable hv801    "Time interview started (hhmm - 24 hour clock)"
label variable hv802    "Time interview ended (hhmm - 24 hour clock)"
label variable hv803    "Length of interview in minutes"
label variable hv804    "Number of visits for biomarker"
label variable hv807d   "Day of biomarker visit"
label variable hv807m   "Month of biomarker visit"
label variable hv807y   "Year of biomarker visit"
label variable hv807c   "Date of biomarker (CMC)"
label variable hv807a   "Date of biomarker Century Day Code (CDC)"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv201a   "NA - Water not available for at least a day last two weeks"
label variable hv204    "Time to get to water source (minutes)"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Number of rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of household"
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone (land-line)"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Has mosquito bed net for sleeping"
label variable hv228    "Children under 5 slept under mosquito bed net last night"
label variable hv235    "Location of source for water"
label variable hv238    "Number of households sharing toilet"
label variable hv243a   "Has mobile telephone"
label variable hv243b   "Has watch"
label variable hv243c   "Has animal-drawn cart"
label variable hv243d   "Has boat with a motor"
label variable hv243e   "Has a computer"
label variable hv244    "Owns land usable for agriculture"
label variable hv245    "Hectares of agricultural land (1 decimal)"
label variable hv246    "Owns livestock, herds or farm animals"
label variable hv246a   "NA - Owns cattle"
label variable hv246b   "NA - Owns cows/ bulls"
label variable hv246c   "Owns horses/ donkeys/ mules"
label variable hv246d   "Owns goats"
label variable hv246e   "Owns sheep"
label variable hv246f   "Owns chickens/poultry"
label variable hv246g   "Owns exotic/cross-breed cattle"
label variable hv246h   "Owns local cattle"
label variable hv246i   "Owns pigs"
label variable hv246j   "NA - Owns CS"
label variable hv246k   "NA - Owns CS"
label variable hv247    "Has bank account"
label variable hv253    "Has dwelling been sprayed against mosquitoes in last 12 months"
label variable hv253a   "Dwelling sprayed by: government worker/program"
label variable hv253b   "Dwelling sprayed by: private company"
label variable hv253c   "Dwelling sprayed by: NGO"
label variable hv253d   "NA - Dwelling sprayed by: CS"
label variable hv253e   "NA - Dwelling sprayed by: CS"
label variable hv253f   "NA - Dwelling sprayed by: CS"
label variable hv253g   "NA - Dwelling sprayed by: CS"
label variable hv253h   "NA - Dwelling sprayed by: CS"
label variable hv253x   "Dwelling sprayed by: other"
label variable hv253z   "Dwelling sprayed by: don't know"
label variable hv270    "Wealth index combined"
label variable hv271    "Wealth index factor score combined (5 decimals)"
label variable hv270a   "Wealth index for urban/rural"
label variable hv271a   "Wealth index factor score for urban/rural (5 decimals)"
label variable hml1     "Number of mosquito bed nets"
label variable hml1a    "Number of mosquito bed nets with specific information"
label variable hml2     "Number of children under mosquito bed net previous night"
label variable shdistrict "District"
label variable shrefugee "Refugee settlements"
label variable sh114g   "Has cassette/CD/DVD player"
label variable sh114h   "Has table"
label variable sh114i   "Has chair"
label variable sh114j   "Has sofa set"
label variable sh114k   "Has bed"
label variable sh114l   "Has cupboard"
label variable sh114m   "Has clock"
label variable sh115h   "Has boat without a motor"
label variable sh117a   "Months ago dwelling was last sprayed"
label variable sh117c   "Paid for dwelling to be sprayed"
label variable sh118    "CHW/CMD/VHT who distributes malaria medicine in community"
label variable sh118a   "CHW currently has malaria medicine available"
label variable hvidx_01 "Line number"
label variable hvidx_02 "Line number"
label variable hvidx_03 "Line number"
label variable hvidx_04 "Line number"
label variable hvidx_05 "Line number"
label variable hvidx_06 "Line number"
label variable hvidx_07 "Line number"
label variable hvidx_08 "Line number"
label variable hvidx_09 "Line number"
label variable hvidx_10 "Line number"
label variable hvidx_11 "Line number"
label variable hvidx_12 "Line number"
label variable hvidx_13 "Line number"
label variable hvidx_14 "Line number"
label variable hvidx_15 "Line number"
label variable hvidx_16 "Line number"
label variable hvidx_17 "Line number"
label variable hvidx_18 "Line number"
label variable hvidx_19 "Line number"
label variable hvidx_20 "Line number"
label variable hvidx_21 "Line number"
label variable hvidx_22 "Line number"
label variable hvidx_23 "Line number"
label variable hvidx_24 "Line number"
label variable hvidx_25 "Line number"
label variable hvidx_26 "Line number"
label variable hvidx_27 "Line number"
label variable hvidx_28 "Line number"
label variable hvidx_29 "Line number"
label variable hvidx_30 "Line number"
label variable hvidx_31 "Line number"
label variable hvidx_32 "Line number"
label variable hvidx_33 "Line number"
label variable hvidx_34 "Line number"
label variable hvidx_35 "Line number"
label variable hvidx_36 "Line number"
label variable hv101_01 "Relationship to head"
label variable hv101_02 "Relationship to head"
label variable hv101_03 "Relationship to head"
label variable hv101_04 "Relationship to head"
label variable hv101_05 "Relationship to head"
label variable hv101_06 "Relationship to head"
label variable hv101_07 "Relationship to head"
label variable hv101_08 "Relationship to head"
label variable hv101_09 "Relationship to head"
label variable hv101_10 "Relationship to head"
label variable hv101_11 "Relationship to head"
label variable hv101_12 "Relationship to head"
label variable hv101_13 "Relationship to head"
label variable hv101_14 "Relationship to head"
label variable hv101_15 "Relationship to head"
label variable hv101_16 "Relationship to head"
label variable hv101_17 "Relationship to head"
label variable hv101_18 "Relationship to head"
label variable hv101_19 "Relationship to head"
label variable hv101_20 "Relationship to head"
label variable hv101_21 "Relationship to head"
label variable hv101_22 "Relationship to head"
label variable hv101_23 "Relationship to head"
label variable hv101_24 "Relationship to head"
label variable hv101_25 "Relationship to head"
label variable hv101_26 "Relationship to head"
label variable hv101_27 "Relationship to head"
label variable hv101_28 "Relationship to head"
label variable hv101_29 "Relationship to head"
label variable hv101_30 "Relationship to head"
label variable hv101_31 "Relationship to head"
label variable hv101_32 "Relationship to head"
label variable hv101_33 "Relationship to head"
label variable hv101_34 "Relationship to head"
label variable hv101_35 "Relationship to head"
label variable hv101_36 "Relationship to head"
label variable hv102_01 "Usual resident"
label variable hv102_02 "Usual resident"
label variable hv102_03 "Usual resident"
label variable hv102_04 "Usual resident"
label variable hv102_05 "Usual resident"
label variable hv102_06 "Usual resident"
label variable hv102_07 "Usual resident"
label variable hv102_08 "Usual resident"
label variable hv102_09 "Usual resident"
label variable hv102_10 "Usual resident"
label variable hv102_11 "Usual resident"
label variable hv102_12 "Usual resident"
label variable hv102_13 "Usual resident"
label variable hv102_14 "Usual resident"
label variable hv102_15 "Usual resident"
label variable hv102_16 "Usual resident"
label variable hv102_17 "Usual resident"
label variable hv102_18 "Usual resident"
label variable hv102_19 "Usual resident"
label variable hv102_20 "Usual resident"
label variable hv102_21 "Usual resident"
label variable hv102_22 "Usual resident"
label variable hv102_23 "Usual resident"
label variable hv102_24 "Usual resident"
label variable hv102_25 "Usual resident"
label variable hv102_26 "Usual resident"
label variable hv102_27 "Usual resident"
label variable hv102_28 "Usual resident"
label variable hv102_29 "Usual resident"
label variable hv102_30 "Usual resident"
label variable hv102_31 "Usual resident"
label variable hv102_32 "Usual resident"
label variable hv102_33 "Usual resident"
label variable hv102_34 "Usual resident"
label variable hv102_35 "Usual resident"
label variable hv102_36 "Usual resident"
label variable hv103_01 "Slept last night"
label variable hv103_02 "Slept last night"
label variable hv103_03 "Slept last night"
label variable hv103_04 "Slept last night"
label variable hv103_05 "Slept last night"
label variable hv103_06 "Slept last night"
label variable hv103_07 "Slept last night"
label variable hv103_08 "Slept last night"
label variable hv103_09 "Slept last night"
label variable hv103_10 "Slept last night"
label variable hv103_11 "Slept last night"
label variable hv103_12 "Slept last night"
label variable hv103_13 "Slept last night"
label variable hv103_14 "Slept last night"
label variable hv103_15 "Slept last night"
label variable hv103_16 "Slept last night"
label variable hv103_17 "Slept last night"
label variable hv103_18 "Slept last night"
label variable hv103_19 "Slept last night"
label variable hv103_20 "Slept last night"
label variable hv103_21 "Slept last night"
label variable hv103_22 "Slept last night"
label variable hv103_23 "Slept last night"
label variable hv103_24 "Slept last night"
label variable hv103_25 "Slept last night"
label variable hv103_26 "Slept last night"
label variable hv103_27 "Slept last night"
label variable hv103_28 "Slept last night"
label variable hv103_29 "Slept last night"
label variable hv103_30 "Slept last night"
label variable hv103_31 "Slept last night"
label variable hv103_32 "Slept last night"
label variable hv103_33 "Slept last night"
label variable hv103_34 "Slept last night"
label variable hv103_35 "Slept last night"
label variable hv103_36 "Slept last night"
label variable hv104_01 "Sex of household member"
label variable hv104_02 "Sex of household member"
label variable hv104_03 "Sex of household member"
label variable hv104_04 "Sex of household member"
label variable hv104_05 "Sex of household member"
label variable hv104_06 "Sex of household member"
label variable hv104_07 "Sex of household member"
label variable hv104_08 "Sex of household member"
label variable hv104_09 "Sex of household member"
label variable hv104_10 "Sex of household member"
label variable hv104_11 "Sex of household member"
label variable hv104_12 "Sex of household member"
label variable hv104_13 "Sex of household member"
label variable hv104_14 "Sex of household member"
label variable hv104_15 "Sex of household member"
label variable hv104_16 "Sex of household member"
label variable hv104_17 "Sex of household member"
label variable hv104_18 "Sex of household member"
label variable hv104_19 "Sex of household member"
label variable hv104_20 "Sex of household member"
label variable hv104_21 "Sex of household member"
label variable hv104_22 "Sex of household member"
label variable hv104_23 "Sex of household member"
label variable hv104_24 "Sex of household member"
label variable hv104_25 "Sex of household member"
label variable hv104_26 "Sex of household member"
label variable hv104_27 "Sex of household member"
label variable hv104_28 "Sex of household member"
label variable hv104_29 "Sex of household member"
label variable hv104_30 "Sex of household member"
label variable hv104_31 "Sex of household member"
label variable hv104_32 "Sex of household member"
label variable hv104_33 "Sex of household member"
label variable hv104_34 "Sex of household member"
label variable hv104_35 "Sex of household member"
label variable hv104_36 "Sex of household member"
label variable hv105_01 "Age of household members"
label variable hv105_02 "Age of household members"
label variable hv105_03 "Age of household members"
label variable hv105_04 "Age of household members"
label variable hv105_05 "Age of household members"
label variable hv105_06 "Age of household members"
label variable hv105_07 "Age of household members"
label variable hv105_08 "Age of household members"
label variable hv105_09 "Age of household members"
label variable hv105_10 "Age of household members"
label variable hv105_11 "Age of household members"
label variable hv105_12 "Age of household members"
label variable hv105_13 "Age of household members"
label variable hv105_14 "Age of household members"
label variable hv105_15 "Age of household members"
label variable hv105_16 "Age of household members"
label variable hv105_17 "Age of household members"
label variable hv105_18 "Age of household members"
label variable hv105_19 "Age of household members"
label variable hv105_20 "Age of household members"
label variable hv105_21 "Age of household members"
label variable hv105_22 "Age of household members"
label variable hv105_23 "Age of household members"
label variable hv105_24 "Age of household members"
label variable hv105_25 "Age of household members"
label variable hv105_26 "Age of household members"
label variable hv105_27 "Age of household members"
label variable hv105_28 "Age of household members"
label variable hv105_29 "Age of household members"
label variable hv105_30 "Age of household members"
label variable hv105_31 "Age of household members"
label variable hv105_32 "Age of household members"
label variable hv105_33 "Age of household members"
label variable hv105_34 "Age of household members"
label variable hv105_35 "Age of household members"
label variable hv105_36 "Age of household members"
label variable hv117_01 "Eligibility for female interview"
label variable hv117_02 "Eligibility for female interview"
label variable hv117_03 "Eligibility for female interview"
label variable hv117_04 "Eligibility for female interview"
label variable hv117_05 "Eligibility for female interview"
label variable hv117_06 "Eligibility for female interview"
label variable hv117_07 "Eligibility for female interview"
label variable hv117_08 "Eligibility for female interview"
label variable hv117_09 "Eligibility for female interview"
label variable hv117_10 "Eligibility for female interview"
label variable hv117_11 "Eligibility for female interview"
label variable hv117_12 "Eligibility for female interview"
label variable hv117_13 "Eligibility for female interview"
label variable hv117_14 "Eligibility for female interview"
label variable hv117_15 "Eligibility for female interview"
label variable hv117_16 "Eligibility for female interview"
label variable hv117_17 "Eligibility for female interview"
label variable hv117_18 "Eligibility for female interview"
label variable hv117_19 "Eligibility for female interview"
label variable hv117_20 "Eligibility for female interview"
label variable hv117_21 "Eligibility for female interview"
label variable hv117_22 "Eligibility for female interview"
label variable hv117_23 "Eligibility for female interview"
label variable hv117_24 "Eligibility for female interview"
label variable hv117_25 "Eligibility for female interview"
label variable hv117_26 "Eligibility for female interview"
label variable hv117_27 "Eligibility for female interview"
label variable hv117_28 "Eligibility for female interview"
label variable hv117_29 "Eligibility for female interview"
label variable hv117_30 "Eligibility for female interview"
label variable hv117_31 "Eligibility for female interview"
label variable hv117_32 "Eligibility for female interview"
label variable hv117_33 "Eligibility for female interview"
label variable hv117_34 "Eligibility for female interview"
label variable hv117_35 "Eligibility for female interview"
label variable hv117_36 "Eligibility for female interview"
label variable hv120_01 "Children eligibility for height/weight and hemoglobin"
label variable hv120_02 "Children eligibility for height/weight and hemoglobin"
label variable hv120_03 "Children eligibility for height/weight and hemoglobin"
label variable hv120_04 "Children eligibility for height/weight and hemoglobin"
label variable hv120_05 "Children eligibility for height/weight and hemoglobin"
label variable hv120_06 "Children eligibility for height/weight and hemoglobin"
label variable hv120_07 "Children eligibility for height/weight and hemoglobin"
label variable hv120_08 "Children eligibility for height/weight and hemoglobin"
label variable hv120_09 "Children eligibility for height/weight and hemoglobin"
label variable hv120_10 "Children eligibility for height/weight and hemoglobin"
label variable hv120_11 "Children eligibility for height/weight and hemoglobin"
label variable hv120_12 "Children eligibility for height/weight and hemoglobin"
label variable hv120_13 "Children eligibility for height/weight and hemoglobin"
label variable hv120_14 "Children eligibility for height/weight and hemoglobin"
label variable hv120_15 "Children eligibility for height/weight and hemoglobin"
label variable hv120_16 "Children eligibility for height/weight and hemoglobin"
label variable hv120_17 "Children eligibility for height/weight and hemoglobin"
label variable hv120_18 "Children eligibility for height/weight and hemoglobin"
label variable hv120_19 "Children eligibility for height/weight and hemoglobin"
label variable hv120_20 "Children eligibility for height/weight and hemoglobin"
label variable hv120_21 "Children eligibility for height/weight and hemoglobin"
label variable hv120_22 "Children eligibility for height/weight and hemoglobin"
label variable hv120_23 "Children eligibility for height/weight and hemoglobin"
label variable hv120_24 "Children eligibility for height/weight and hemoglobin"
label variable hv120_25 "Children eligibility for height/weight and hemoglobin"
label variable hv120_26 "Children eligibility for height/weight and hemoglobin"
label variable hv120_27 "Children eligibility for height/weight and hemoglobin"
label variable hv120_28 "Children eligibility for height/weight and hemoglobin"
label variable hv120_29 "Children eligibility for height/weight and hemoglobin"
label variable hv120_30 "Children eligibility for height/weight and hemoglobin"
label variable hv120_31 "Children eligibility for height/weight and hemoglobin"
label variable hv120_32 "Children eligibility for height/weight and hemoglobin"
label variable hv120_33 "Children eligibility for height/weight and hemoglobin"
label variable hv120_34 "Children eligibility for height/weight and hemoglobin"
label variable hv120_35 "Children eligibility for height/weight and hemoglobin"
label variable hv120_36 "Children eligibility for height/weight and hemoglobin"
label variable hc0_1    "Index to Household Schedule"
label variable hc0_2    "Index to Household Schedule"
label variable hc0_3    "Index to Household Schedule"
label variable hc0_4    "Index to Household Schedule"
label variable hc0_5    "Index to Household Schedule"
label variable hc0_6    "Index to Household Schedule"
label variable hc0_7    "Index to Household Schedule"
label variable hc1_1    "Child's age in months"
label variable hc1_2    "Child's age in months"
label variable hc1_3    "Child's age in months"
label variable hc1_4    "Child's age in months"
label variable hc1_5    "Child's age in months"
label variable hc1_6    "Child's age in months"
label variable hc1_7    "Child's age in months"
label variable hc1a_1   "Child's age in days"
label variable hc1a_2   "Child's age in days"
label variable hc1a_3   "Child's age in days"
label variable hc1a_4   "Child's age in days"
label variable hc1a_5   "Child's age in days"
label variable hc1a_6   "Child's age in days"
label variable hc1a_7   "Child's age in days"
label variable hc16_1   "Day of birth"
label variable hc16_2   "Day of birth"
label variable hc16_3   "Day of birth"
label variable hc16_4   "Day of birth"
label variable hc16_5   "Day of birth"
label variable hc16_6   "Day of birth"
label variable hc16_7   "Day of birth"
label variable hc17_1   "Date measured (day)"
label variable hc17_2   "Date measured (day)"
label variable hc17_3   "Date measured (day)"
label variable hc17_4   "Date measured (day)"
label variable hc17_5   "Date measured (day)"
label variable hc17_6   "Date measured (day)"
label variable hc17_7   "Date measured (day)"
label variable hc18_1   "Date measured (month)"
label variable hc18_2   "Date measured (month)"
label variable hc18_3   "Date measured (month)"
label variable hc18_4   "Date measured (month)"
label variable hc18_5   "Date measured (month)"
label variable hc18_6   "Date measured (month)"
label variable hc18_7   "Date measured (month)"
label variable hc19_1   "Date measured (year)"
label variable hc19_2   "Date measured (year)"
label variable hc19_3   "Date measured (year)"
label variable hc19_4   "Date measured (year)"
label variable hc19_5   "Date measured (year)"
label variable hc19_6   "Date measured (year)"
label variable hc19_7   "Date measured (year)"
label variable hc20_1   "Century Day Code (CDC) of measurement"
label variable hc20_2   "Century Day Code (CDC) of measurement"
label variable hc20_3   "Century Day Code (CDC) of measurement"
label variable hc20_4   "Century Day Code (CDC) of measurement"
label variable hc20_5   "Century Day Code (CDC) of measurement"
label variable hc20_6   "Century Day Code (CDC) of measurement"
label variable hc20_7   "Century Day Code (CDC) of measurement"
label variable hc21_1   "Fieldworker measurer code"
label variable hc21_2   "Fieldworker measurer code"
label variable hc21_3   "Fieldworker measurer code"
label variable hc21_4   "Fieldworker measurer code"
label variable hc21_5   "Fieldworker measurer code"
label variable hc21_6   "Fieldworker measurer code"
label variable hc21_7   "Fieldworker measurer code"
label variable hc27_1   "Sex"
label variable hc27_2   "Sex"
label variable hc27_3   "Sex"
label variable hc27_4   "Sex"
label variable hc27_5   "Sex"
label variable hc27_6   "Sex"
label variable hc27_7   "Sex"
label variable hc30_1   "Month of birth"
label variable hc30_2   "Month of birth"
label variable hc30_3   "Month of birth"
label variable hc30_4   "Month of birth"
label variable hc30_5   "Month of birth"
label variable hc30_6   "Month of birth"
label variable hc30_7   "Month of birth"
label variable hc31_1   "Year of birth"
label variable hc31_2   "Year of birth"
label variable hc31_3   "Year of birth"
label variable hc31_4   "Year of birth"
label variable hc31_5   "Year of birth"
label variable hc31_6   "Year of birth"
label variable hc31_7   "Year of birth"
label variable hc32_1   "Date of birth (CMC)"
label variable hc32_2   "Date of birth (CMC)"
label variable hc32_3   "Date of birth (CMC)"
label variable hc32_4   "Date of birth (CMC)"
label variable hc32_5   "Date of birth (CMC)"
label variable hc32_6   "Date of birth (CMC)"
label variable hc32_7   "Date of birth (CMC)"
label variable hc32a_1  "Century Day Code (CDC) of birth"
label variable hc32a_2  "Century Day Code (CDC) of birth"
label variable hc32a_3  "Century Day Code (CDC) of birth"
label variable hc32a_4  "Century Day Code (CDC) of birth"
label variable hc32a_5  "Century Day Code (CDC) of birth"
label variable hc32a_6  "Century Day Code (CDC) of birth"
label variable hc32a_7  "Century Day Code (CDC) of birth"
label variable hc33_1   "Completeness of HC32 information"
label variable hc33_2   "Completeness of HC32 information"
label variable hc33_3   "Completeness of HC32 information"
label variable hc33_4   "Completeness of HC32 information"
label variable hc33_5   "Completeness of HC32 information"
label variable hc33_6   "Completeness of HC32 information"
label variable hc33_7   "Completeness of HC32 information"
label variable hc51_1   "Line number of parent/caretaker"
label variable hc51_2   "Line number of parent/caretaker"
label variable hc51_3   "Line number of parent/caretaker"
label variable hc51_4   "Line number of parent/caretaker"
label variable hc51_5   "Line number of parent/caretaker"
label variable hc51_6   "Line number of parent/caretaker"
label variable hc51_7   "Line number of parent/caretaker"
label variable hc52_1   "Read consent statement - hemoglobin"
label variable hc52_2   "Read consent statement - hemoglobin"
label variable hc52_3   "Read consent statement - hemoglobin"
label variable hc52_4   "Read consent statement - hemoglobin"
label variable hc52_5   "Read consent statement - hemoglobin"
label variable hc52_6   "Read consent statement - hemoglobin"
label variable hc52_7   "Read consent statement - hemoglobin"
label variable hc53_1   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_2   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_3   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_4   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_5   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_6   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc53_7   "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55_1   "Result of measurement - hemoglobin"
label variable hc55_2   "Result of measurement - hemoglobin"
label variable hc55_3   "Result of measurement - hemoglobin"
label variable hc55_4   "Result of measurement - hemoglobin"
label variable hc55_5   "Result of measurement - hemoglobin"
label variable hc55_6   "Result of measurement - hemoglobin"
label variable hc55_7   "Result of measurement - hemoglobin"
label variable hc56_1   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_2   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_3   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_4   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_5   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_6   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc56_7   "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
label variable hc57_1   "Anemia level"
label variable hc57_2   "Anemia level"
label variable hc57_3   "Anemia level"
label variable hc57_4   "Anemia level"
label variable hc57_5   "Anemia level"
label variable hc57_6   "Anemia level"
label variable hc57_7   "Anemia level"
label variable hc58_1   "NA - Agrees to referral - anemia"
label variable hc58_2   "NA - Agrees to referral - anemia"
label variable hc58_3   "NA - Agrees to referral - anemia"
label variable hc58_4   "NA - Agrees to referral - anemia"
label variable hc58_5   "NA - Agrees to referral - anemia"
label variable hc58_6   "NA - Agrees to referral - anemia"
label variable hc58_7   "NA - Agrees to referral - anemia"
label variable hc60_1   "Mother's line number (woman's questionnaire)"
label variable hc60_2   "Mother's line number (woman's questionnaire)"
label variable hc60_3   "Mother's line number (woman's questionnaire)"
label variable hc60_4   "Mother's line number (woman's questionnaire)"
label variable hc60_5   "Mother's line number (woman's questionnaire)"
label variable hc60_6   "Mother's line number (woman's questionnaire)"
label variable hc60_7   "Mother's line number (woman's questionnaire)"
label variable hc61_1   "Mother's highest educational level"
label variable hc61_2   "Mother's highest educational level"
label variable hc61_3   "Mother's highest educational level"
label variable hc61_4   "Mother's highest educational level"
label variable hc61_5   "Mother's highest educational level"
label variable hc61_6   "Mother's highest educational level"
label variable hc61_7   "Mother's highest educational level"
label variable hc62_1   "Mother's highest year of education"
label variable hc62_2   "Mother's highest year of education"
label variable hc62_3   "Mother's highest year of education"
label variable hc62_4   "Mother's highest year of education"
label variable hc62_5   "Mother's highest year of education"
label variable hc62_6   "Mother's highest year of education"
label variable hc62_7   "Mother's highest year of education"
label variable hc63_1   "Preceding birth interval (months)"
label variable hc63_2   "Preceding birth interval (months)"
label variable hc63_3   "Preceding birth interval (months)"
label variable hc63_4   "Preceding birth interval (months)"
label variable hc63_5   "Preceding birth interval (months)"
label variable hc63_6   "Preceding birth interval (months)"
label variable hc63_7   "Preceding birth interval (months)"
label variable hc64_1   "Birth order number"
label variable hc64_2   "Birth order number"
label variable hc64_3   "Birth order number"
label variable hc64_4   "Birth order number"
label variable hc64_5   "Birth order number"
label variable hc64_6   "Birth order number"
label variable hc64_7   "Birth order number"
label variable hc68_1   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_2   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_3   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_4   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_5   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_6   "Mother's highest educational level (for preliminary and final report)"
label variable hc68_7   "Mother's highest educational level (for preliminary and final report)"
label variable hc70_1   "Height/Age standard deviation (new WHO)"
label variable hc70_2   "Height/Age standard deviation (new WHO)"
label variable hc70_3   "Height/Age standard deviation (new WHO)"
label variable hc70_4   "Height/Age standard deviation (new WHO)"
label variable hc70_5   "Height/Age standard deviation (new WHO)"
label variable hc70_6   "Height/Age standard deviation (new WHO)"
label variable hc70_7   "Height/Age standard deviation (new WHO)"
label variable hc71_1   "Weight/Age standard deviation (new WHO)"
label variable hc71_2   "Weight/Age standard deviation (new WHO)"
label variable hc71_3   "Weight/Age standard deviation (new WHO)"
label variable hc71_4   "Weight/Age standard deviation (new WHO)"
label variable hc71_5   "Weight/Age standard deviation (new WHO)"
label variable hc71_6   "Weight/Age standard deviation (new WHO)"
label variable hc71_7   "Weight/Age standard deviation (new WHO)"
label variable hc72_1   "Weight/Height standard deviation (new WHO)"
label variable hc72_2   "Weight/Height standard deviation (new WHO)"
label variable hc72_3   "Weight/Height standard deviation (new WHO)"
label variable hc72_4   "Weight/Height standard deviation (new WHO)"
label variable hc72_5   "Weight/Height standard deviation (new WHO)"
label variable hc72_6   "Weight/Height standard deviation (new WHO)"
label variable hc72_7   "Weight/Height standard deviation (new WHO)"
label variable hc73_1   "BMI standard deviation (new WHO)"
label variable hc73_2   "BMI standard deviation (new WHO)"
label variable hc73_3   "BMI standard deviation (new WHO)"
label variable hc73_4   "BMI standard deviation (new WHO)"
label variable hc73_5   "BMI standard deviation (new WHO)"
label variable hc73_6   "BMI standard deviation (new WHO)"
label variable hc73_7   "BMI standard deviation (new WHO)"
label variable sb118a_1 "Child has any symptoms: extreme weakness"
label variable sb118a_2 "Child has any symptoms: extreme weakness"
label variable sb118a_3 "Child has any symptoms: extreme weakness"
label variable sb118a_4 "Child has any symptoms: extreme weakness"
label variable sb118a_5 "Child has any symptoms: extreme weakness"
label variable sb118a_6 "Child has any symptoms: extreme weakness"
label variable sb118a_7 "Child has any symptoms: extreme weakness"
label variable sb118b_1 "Child has any symptoms: heart problems"
label variable sb118b_2 "Child has any symptoms: heart problems"
label variable sb118b_3 "Child has any symptoms: heart problems"
label variable sb118b_4 "Child has any symptoms: heart problems"
label variable sb118b_5 "Child has any symptoms: heart problems"
label variable sb118b_6 "Child has any symptoms: heart problems"
label variable sb118b_7 "Child has any symptoms: heart problems"
label variable sb118c_1 "Child has any symptoms: loss of consciousness"
label variable sb118c_2 "Child has any symptoms: loss of consciousness"
label variable sb118c_3 "Child has any symptoms: loss of consciousness"
label variable sb118c_4 "Child has any symptoms: loss of consciousness"
label variable sb118c_5 "Child has any symptoms: loss of consciousness"
label variable sb118c_6 "Child has any symptoms: loss of consciousness"
label variable sb118c_7 "Child has any symptoms: loss of consciousness"
label variable sb118d_1 "Child has any symptoms: rapid or difficult breathing"
label variable sb118d_2 "Child has any symptoms: rapid or difficult breathing"
label variable sb118d_3 "Child has any symptoms: rapid or difficult breathing"
label variable sb118d_4 "Child has any symptoms: rapid or difficult breathing"
label variable sb118d_5 "Child has any symptoms: rapid or difficult breathing"
label variable sb118d_6 "Child has any symptoms: rapid or difficult breathing"
label variable sb118d_7 "Child has any symptoms: rapid or difficult breathing"
label variable sb118e_1 "Child has any symptoms: seizures"
label variable sb118e_2 "Child has any symptoms: seizures"
label variable sb118e_3 "Child has any symptoms: seizures"
label variable sb118e_4 "Child has any symptoms: seizures"
label variable sb118e_5 "Child has any symptoms: seizures"
label variable sb118e_6 "Child has any symptoms: seizures"
label variable sb118e_7 "Child has any symptoms: seizures"
label variable sb118f_1 "Child has any symptoms: abnormal bleeding"
label variable sb118f_2 "Child has any symptoms: abnormal bleeding"
label variable sb118f_3 "Child has any symptoms: abnormal bleeding"
label variable sb118f_4 "Child has any symptoms: abnormal bleeding"
label variable sb118f_5 "Child has any symptoms: abnormal bleeding"
label variable sb118f_6 "Child has any symptoms: abnormal bleeding"
label variable sb118f_7 "Child has any symptoms: abnormal bleeding"
label variable sb118g_1 "Child has any symptoms: jaundice or yellow skin"
label variable sb118g_2 "Child has any symptoms: jaundice or yellow skin"
label variable sb118g_3 "Child has any symptoms: jaundice or yellow skin"
label variable sb118g_4 "Child has any symptoms: jaundice or yellow skin"
label variable sb118g_5 "Child has any symptoms: jaundice or yellow skin"
label variable sb118g_6 "Child has any symptoms: jaundice or yellow skin"
label variable sb118g_7 "Child has any symptoms: jaundice or yellow skin"
label variable sb118h_1 "Child has any symptoms: dark urine"
label variable sb118h_2 "Child has any symptoms: dark urine"
label variable sb118h_3 "Child has any symptoms: dark urine"
label variable sb118h_4 "Child has any symptoms: dark urine"
label variable sb118h_5 "Child has any symptoms: dark urine"
label variable sb118h_6 "Child has any symptoms: dark urine"
label variable sb118h_7 "Child has any symptoms: dark urine"
label variable sb121_1  "Child has been given malaria medication in past two weeks"
label variable sb121_2  "Child has been given malaria medication in past two weeks"
label variable sb121_3  "Child has been given malaria medication in past two weeks"
label variable sb121_4  "Child has been given malaria medication in past two weeks"
label variable sb121_5  "Child has been given malaria medication in past two weeks"
label variable sb121_6  "Child has been given malaria medication in past two weeks"
label variable sb121_7  "Child has been given malaria medication in past two weeks"
label variable sb125_1  "Malaria medication accepted"
label variable sb125_2  "Malaria medication accepted"
label variable sb125_3  "Malaria medication accepted"
label variable sb125_4  "Malaria medication accepted"
label variable sb125_5  "Malaria medication accepted"
label variable sb125_6  "Malaria medication accepted"
label variable sb125_7  "Malaria medication accepted"
label variable hmlidx_1 "Mosquito Bed Net Designation Number"
label variable hmlidx_2 "Mosquito Bed Net Designation Number"
label variable hmlidx_3 "Mosquito Bed Net Designation Number"
label variable hmlidx_4 "Mosquito Bed Net Designation Number"
label variable hmlidx_5 "Mosquito Bed Net Designation Number"
label variable hmlidx_6 "Mosquito Bed Net Designation Number"
label variable hmlidx_7 "Mosquito Bed Net Designation Number"
label variable hml3_1   "Net observed by interviewer"
label variable hml3_2   "Net observed by interviewer"
label variable hml3_3   "Net observed by interviewer"
label variable hml3_4   "Net observed by interviewer"
label variable hml3_5   "Net observed by interviewer"
label variable hml3_6   "Net observed by interviewer"
label variable hml3_7   "Net observed by interviewer"
label variable hml4_1   "Months ago net obtained"
label variable hml4_2   "Months ago net obtained"
label variable hml4_3   "Months ago net obtained"
label variable hml4_4   "Months ago net obtained"
label variable hml4_5   "Months ago net obtained"
label variable hml4_6   "Months ago net obtained"
label variable hml4_7   "Months ago net obtained"
label variable hml5_1   "NA - Net treated with insecticide when bought"
label variable hml5_2   "NA - Net treated with insecticide when bought"
label variable hml5_3   "NA - Net treated with insecticide when bought"
label variable hml5_4   "NA - Net treated with insecticide when bought"
label variable hml5_5   "NA - Net treated with insecticide when bought"
label variable hml5_6   "NA - Net treated with insecticide when bought"
label variable hml5_7   "NA - Net treated with insecticide when bought"
label variable hml6_1   "NA - Net treatment status"
label variable hml6_2   "NA - Net treatment status"
label variable hml6_3   "NA - Net treatment status"
label variable hml6_4   "NA - Net treatment status"
label variable hml6_5   "NA - Net treatment status"
label variable hml6_6   "NA - Net treatment status"
label variable hml6_7   "NA - Net treatment status"
label variable hml7_1   "Brand of net"
label variable hml7_2   "Brand of net"
label variable hml7_3   "Brand of net"
label variable hml7_4   "Brand of net"
label variable hml7_5   "Brand of net"
label variable hml7_6   "Brand of net"
label variable hml7_7   "Brand of net"
label variable hml8_1   "Net treated since received"
label variable hml8_2   "Net treated since received"
label variable hml8_3   "Net treated since received"
label variable hml8_4   "Net treated since received"
label variable hml8_5   "Net treated since received"
label variable hml8_6   "Net treated since received"
label variable hml8_7   "Net treated since received"
label variable hml9_1   "NA - Time since last re-treatment (months)"
label variable hml9_2   "NA - Time since last re-treatment (months)"
label variable hml9_3   "NA - Time since last re-treatment (months)"
label variable hml9_4   "NA - Time since last re-treatment (months)"
label variable hml9_5   "NA - Time since last re-treatment (months)"
label variable hml9_6   "NA - Time since last re-treatment (months)"
label variable hml9_7   "NA - Time since last re-treatment (months)"
label variable hml10_1  "Insecticide-Treated Net (ITN)"
label variable hml10_2  "Insecticide-Treated Net (ITN)"
label variable hml10_3  "Insecticide-Treated Net (ITN)"
label variable hml10_4  "Insecticide-Treated Net (ITN)"
label variable hml10_5  "Insecticide-Treated Net (ITN)"
label variable hml10_6  "Insecticide-Treated Net (ITN)"
label variable hml10_7  "Insecticide-Treated Net (ITN)"
label variable hml11_1  "Number of persons who slept under this net"
label variable hml11_2  "Number of persons who slept under this net"
label variable hml11_3  "Number of persons who slept under this net"
label variable hml11_4  "Number of persons who slept under this net"
label variable hml11_5  "Number of persons who slept under this net"
label variable hml11_6  "Number of persons who slept under this net"
label variable hml11_7  "Number of persons who slept under this net"
label variable hml21_1  "Someone slept under this net last night"
label variable hml21_2  "Someone slept under this net last night"
label variable hml21_3  "Someone slept under this net last night"
label variable hml21_4  "Someone slept under this net last night"
label variable hml21_5  "Someone slept under this net last night"
label variable hml21_6  "Someone slept under this net last night"
label variable hml21_7  "Someone slept under this net last night"
label variable hmla_1   "Line number of person who slept in this net"
label variable hmla_2   "Line number of person who slept in this net"
label variable hmla_3   "Line number of person who slept in this net"
label variable hmla_4   "Line number of person who slept in this net"
label variable hmla_5   "Line number of person who slept in this net"
label variable hmla_6   "Line number of person who slept in this net"
label variable hmla_7   "Line number of person who slept in this net"
label variable hmlb_1   "Line number of person who slept in this net"
label variable hmlb_2   "Line number of person who slept in this net"
label variable hmlb_3   "Line number of person who slept in this net"
label variable hmlb_4   "Line number of person who slept in this net"
label variable hmlb_5   "Line number of person who slept in this net"
label variable hmlb_6   "Line number of person who slept in this net"
label variable hmlb_7   "Line number of person who slept in this net"
label variable hmlc_1   "Line number of person who slept in this net"
label variable hmlc_2   "Line number of person who slept in this net"
label variable hmlc_3   "Line number of person who slept in this net"
label variable hmlc_4   "Line number of person who slept in this net"
label variable hmlc_5   "Line number of person who slept in this net"
label variable hmlc_6   "Line number of person who slept in this net"
label variable hmlc_7   "Line number of person who slept in this net"
label variable hmld_1   "Line number of person who slept in this net"
label variable hmld_2   "Line number of person who slept in this net"
label variable hmld_3   "Line number of person who slept in this net"
label variable hmld_4   "Line number of person who slept in this net"
label variable hmld_5   "Line number of person who slept in this net"
label variable hmld_6   "Line number of person who slept in this net"
label variable hmld_7   "Line number of person who slept in this net"
label variable hmle_1   "NA - Line number of person who slept in this net"
label variable hmle_2   "NA - Line number of person who slept in this net"
label variable hmle_3   "NA - Line number of person who slept in this net"
label variable hmle_4   "NA - Line number of person who slept in this net"
label variable hmle_5   "NA - Line number of person who slept in this net"
label variable hmle_6   "NA - Line number of person who slept in this net"
label variable hmle_7   "NA - Line number of person who slept in this net"
label variable hml22_1  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_2  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_3  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_4  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_5  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_6  "Obtained net from campaign, antenatal or immunization visit"
label variable hml22_7  "Obtained net from campaign, antenatal or immunization visit"
label variable hml23_1  "Place where net was obtained"
label variable hml23_2  "Place where net was obtained"
label variable hml23_3  "Place where net was obtained"
label variable hml23_4  "Place where net was obtained"
label variable hml23_5  "Place where net was obtained"
label variable hml23_6  "Place where net was obtained"
label variable hml23_7  "Place where net was obtained"
label variable sh128aa_1 "Reason net was not used: too hot"
label variable sh128aa_2 "Reason net was not used: too hot"
label variable sh128aa_3 "Reason net was not used: too hot"
label variable sh128aa_4 "Reason net was not used: too hot"
label variable sh128aa_5 "Reason net was not used: too hot"
label variable sh128aa_6 "Reason net was not used: too hot"
label variable sh128aa_7 "Reason net was not used: too hot"
label variable sh128ab_1 "Reason net was not used: don't like smell"
label variable sh128ab_2 "Reason net was not used: don't like smell"
label variable sh128ab_3 "Reason net was not used: don't like smell"
label variable sh128ab_4 "Reason net was not used: don't like smell"
label variable sh128ab_5 "Reason net was not used: don't like smell"
label variable sh128ab_6 "Reason net was not used: don't like smell"
label variable sh128ab_7 "Reason net was not used: don't like smell"
label variable sh128ac_1 "Reason net was not used: no mosquitos"
label variable sh128ac_2 "Reason net was not used: no mosquitos"
label variable sh128ac_3 "Reason net was not used: no mosquitos"
label variable sh128ac_4 "Reason net was not used: no mosquitos"
label variable sh128ac_5 "Reason net was not used: no mosquitos"
label variable sh128ac_6 "Reason net was not used: no mosquitos"
label variable sh128ac_7 "Reason net was not used: no mosquitos"
label variable sh128ad_1 "Reason net was not used: net too old/many holes"
label variable sh128ad_2 "Reason net was not used: net too old/many holes"
label variable sh128ad_3 "Reason net was not used: net too old/many holes"
label variable sh128ad_4 "Reason net was not used: net too old/many holes"
label variable sh128ad_5 "Reason net was not used: net too old/many holes"
label variable sh128ad_6 "Reason net was not used: net too old/many holes"
label variable sh128ad_7 "Reason net was not used: net too old/many holes"
label variable sh128ae_1 "Reason net was not used: unable to hang"
label variable sh128ae_2 "Reason net was not used: unable to hang"
label variable sh128ae_3 "Reason net was not used: unable to hang"
label variable sh128ae_4 "Reason net was not used: unable to hang"
label variable sh128ae_5 "Reason net was not used: unable to hang"
label variable sh128ae_6 "Reason net was not used: unable to hang"
label variable sh128ae_7 "Reason net was not used: unable to hang"
label variable sh128af_1 "Reason net was not used: no place to hang"
label variable sh128af_2 "Reason net was not used: no place to hang"
label variable sh128af_3 "Reason net was not used: no place to hang"
label variable sh128af_4 "Reason net was not used: no place to hang"
label variable sh128af_5 "Reason net was not used: no place to hang"
label variable sh128af_6 "Reason net was not used: no place to hang"
label variable sh128af_7 "Reason net was not used: no place to hang"
label variable sh128ag_1 "Reason net was not used: chemicals in net not safe"
label variable sh128ag_2 "Reason net was not used: chemicals in net not safe"
label variable sh128ag_3 "Reason net was not used: chemicals in net not safe"
label variable sh128ag_4 "Reason net was not used: chemicals in net not safe"
label variable sh128ag_5 "Reason net was not used: chemicals in net not safe"
label variable sh128ag_6 "Reason net was not used: chemicals in net not safe"
label variable sh128ag_7 "Reason net was not used: chemicals in net not safe"
label variable sh128ah_1 "Reason net was not used: saving for rainy season"
label variable sh128ah_2 "Reason net was not used: saving for rainy season"
label variable sh128ah_3 "Reason net was not used: saving for rainy season"
label variable sh128ah_4 "Reason net was not used: saving for rainy season"
label variable sh128ah_5 "Reason net was not used: saving for rainy season"
label variable sh128ah_6 "Reason net was not used: saving for rainy season"
label variable sh128ah_7 "Reason net was not used: saving for rainy season"
label variable sh128ai_1 "Reason net was not used: saving to replace other net"
label variable sh128ai_2 "Reason net was not used: saving to replace other net"
label variable sh128ai_3 "Reason net was not used: saving to replace other net"
label variable sh128ai_4 "Reason net was not used: saving to replace other net"
label variable sh128ai_5 "Reason net was not used: saving to replace other net"
label variable sh128ai_6 "Reason net was not used: saving to replace other net"
label variable sh128ai_7 "Reason net was not used: saving to replace other net"
label variable sh128aj_1 "Reason net was not used: material too hard/rough"
label variable sh128aj_2 "Reason net was not used: material too hard/rough"
label variable sh128aj_3 "Reason net was not used: material too hard/rough"
label variable sh128aj_4 "Reason net was not used: material too hard/rough"
label variable sh128aj_5 "Reason net was not used: material too hard/rough"
label variable sh128aj_6 "Reason net was not used: material too hard/rough"
label variable sh128aj_7 "Reason net was not used: material too hard/rough"
label variable sh128ak_1 "Reason net was not used: usual user didn't sleep here"
label variable sh128ak_2 "Reason net was not used: usual user didn't sleep here"
label variable sh128ak_3 "Reason net was not used: usual user didn't sleep here"
label variable sh128ak_4 "Reason net was not used: usual user didn't sleep here"
label variable sh128ak_5 "Reason net was not used: usual user didn't sleep here"
label variable sh128ak_6 "Reason net was not used: usual user didn't sleep here"
label variable sh128ak_7 "Reason net was not used: usual user didn't sleep here"
label variable sh128ax_1 "Reason net was not used: other reason"
label variable sh128ax_2 "Reason net was not used: other reason"
label variable sh128ax_3 "Reason net was not used: other reason"
label variable sh128ax_4 "Reason net was not used: other reason"
label variable sh128ax_5 "Reason net was not used: other reason"
label variable sh128ax_6 "Reason net was not used: other reason"
label variable sh128ax_7 "Reason net was not used: other reason"
label variable sh128az_1 "Reason net was not used: don't know"
label variable sh128az_2 "Reason net was not used: don't know"
label variable sh128az_3 "Reason net was not used: don't know"
label variable sh128az_4 "Reason net was not used: don't know"
label variable sh128az_5 "Reason net was not used: don't know"
label variable sh128az_6 "Reason net was not used: don't know"
label variable sh128az_7 "Reason net was not used: don't know"
label variable hmhidx_01 "Index to Household Schedule"
label variable hmhidx_02 "Index to Household Schedule"
label variable hmhidx_03 "Index to Household Schedule"
label variable hmhidx_04 "Index to Household Schedule"
label variable hmhidx_05 "Index to Household Schedule"
label variable hmhidx_06 "Index to Household Schedule"
label variable hmhidx_07 "Index to Household Schedule"
label variable hmhidx_08 "Index to Household Schedule"
label variable hmhidx_09 "Index to Household Schedule"
label variable hmhidx_10 "Index to Household Schedule"
label variable hmhidx_11 "Index to Household Schedule"
label variable hmhidx_12 "Index to Household Schedule"
label variable hmhidx_13 "Index to Household Schedule"
label variable hmhidx_14 "Index to Household Schedule"
label variable hmhidx_15 "Index to Household Schedule"
label variable hmhidx_16 "Index to Household Schedule"
label variable hmhidx_17 "Index to Household Schedule"
label variable hmhidx_18 "Index to Household Schedule"
label variable hmhidx_19 "Index to Household Schedule"
label variable hmhidx_20 "Index to Household Schedule"
label variable hmhidx_21 "Index to Household Schedule"
label variable hmhidx_22 "Index to Household Schedule"
label variable hmhidx_23 "Index to Household Schedule"
label variable hmhidx_24 "Index to Household Schedule"
label variable hmhidx_25 "Index to Household Schedule"
label variable hmhidx_26 "Index to Household Schedule"
label variable hmhidx_27 "Index to Household Schedule"
label variable hmhidx_28 "Index to Household Schedule"
label variable hmhidx_29 "Index to Household Schedule"
label variable hmhidx_30 "Index to Household Schedule"
label variable hmhidx_31 "Index to Household Schedule"
label variable hmhidx_32 "Index to Household Schedule"
label variable hmhidx_33 "Index to Household Schedule"
label variable hmhidx_34 "Index to Household Schedule"
label variable hmhidx_35 "Index to Household Schedule"
label variable hmhidx_36 "Index to Household Schedule"
label variable hml12_01 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_02 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_03 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_04 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_05 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_06 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_07 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_08 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_09 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_10 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_11 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_12 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_13 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_14 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_15 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_16 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_17 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_18 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_19 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_20 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_21 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_22 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_23 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_24 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_25 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_26 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_27 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_28 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_29 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_30 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_31 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_32 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_33 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_34 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_35 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml12_36 "Type of Mosquito Bed Net(s) person slept under last night"
label variable hml13_01 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_02 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_03 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_04 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_05 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_06 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_07 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_08 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_09 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_10 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_11 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_12 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_13 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_14 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_15 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_16 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_17 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_18 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_19 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_20 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_21 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_22 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_23 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_24 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_25 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_26 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_27 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_28 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_29 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_30 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_31 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_32 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_33 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_34 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_35 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml13_36 "Net Designation Number (HMLIDX) for 1st net person slept under last night"
label variable hml14_01 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_02 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_03 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_04 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_05 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_06 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_07 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_08 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_09 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_10 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_11 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_12 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_13 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_14 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_15 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_16 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_17 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_18 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_19 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_20 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_21 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_22 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_23 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_24 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_25 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_26 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_27 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_28 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_29 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_30 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_31 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_32 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_33 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_34 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_35 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml14_36 "Net Designation Number (HMLIDX) for 2nd net person slept under last night"
label variable hml15_01 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_02 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_03 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_04 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_05 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_06 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_07 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_08 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_09 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_10 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_11 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_12 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_13 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_14 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_15 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_16 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_17 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_18 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_19 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_20 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_21 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_22 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_23 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_24 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_25 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_26 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_27 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_28 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_29 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_30 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_31 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_32 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_33 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_34 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_35 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml15_36 "NA - Net Designation Number (HMLIDX) for 3rd net person slept under last night"
label variable hml16_01 "Corrected age from Individual file"
label variable hml16_02 "Corrected age from Individual file"
label variable hml16_03 "Corrected age from Individual file"
label variable hml16_04 "Corrected age from Individual file"
label variable hml16_05 "Corrected age from Individual file"
label variable hml16_06 "Corrected age from Individual file"
label variable hml16_07 "Corrected age from Individual file"
label variable hml16_08 "Corrected age from Individual file"
label variable hml16_09 "Corrected age from Individual file"
label variable hml16_10 "Corrected age from Individual file"
label variable hml16_11 "Corrected age from Individual file"
label variable hml16_12 "Corrected age from Individual file"
label variable hml16_13 "Corrected age from Individual file"
label variable hml16_14 "Corrected age from Individual file"
label variable hml16_15 "Corrected age from Individual file"
label variable hml16_16 "Corrected age from Individual file"
label variable hml16_17 "Corrected age from Individual file"
label variable hml16_18 "Corrected age from Individual file"
label variable hml16_19 "Corrected age from Individual file"
label variable hml16_20 "Corrected age from Individual file"
label variable hml16_21 "Corrected age from Individual file"
label variable hml16_22 "Corrected age from Individual file"
label variable hml16_23 "Corrected age from Individual file"
label variable hml16_24 "Corrected age from Individual file"
label variable hml16_25 "Corrected age from Individual file"
label variable hml16_26 "Corrected age from Individual file"
label variable hml16_27 "Corrected age from Individual file"
label variable hml16_28 "Corrected age from Individual file"
label variable hml16_29 "Corrected age from Individual file"
label variable hml16_30 "Corrected age from Individual file"
label variable hml16_31 "Corrected age from Individual file"
label variable hml16_32 "Corrected age from Individual file"
label variable hml16_33 "Corrected age from Individual file"
label variable hml16_34 "Corrected age from Individual file"
label variable hml16_35 "Corrected age from Individual file"
label variable hml16_36 "Corrected age from Individual file"
label variable hml16a_01 "Age in months (for children)"
label variable hml16a_02 "Age in months (for children)"
label variable hml16a_03 "Age in months (for children)"
label variable hml16a_04 "Age in months (for children)"
label variable hml16a_05 "Age in months (for children)"
label variable hml16a_06 "Age in months (for children)"
label variable hml16a_07 "Age in months (for children)"
label variable hml16a_08 "Age in months (for children)"
label variable hml16a_09 "Age in months (for children)"
label variable hml16a_10 "Age in months (for children)"
label variable hml16a_11 "Age in months (for children)"
label variable hml16a_12 "Age in months (for children)"
label variable hml16a_13 "Age in months (for children)"
label variable hml16a_14 "Age in months (for children)"
label variable hml16a_15 "Age in months (for children)"
label variable hml16a_16 "Age in months (for children)"
label variable hml16a_17 "Age in months (for children)"
label variable hml16a_18 "Age in months (for children)"
label variable hml16a_19 "Age in months (for children)"
label variable hml16a_20 "Age in months (for children)"
label variable hml16a_21 "Age in months (for children)"
label variable hml16a_22 "Age in months (for children)"
label variable hml16a_23 "Age in months (for children)"
label variable hml16a_24 "Age in months (for children)"
label variable hml16a_25 "Age in months (for children)"
label variable hml16a_26 "Age in months (for children)"
label variable hml16a_27 "Age in months (for children)"
label variable hml16a_28 "Age in months (for children)"
label variable hml16a_29 "Age in months (for children)"
label variable hml16a_30 "Age in months (for children)"
label variable hml16a_31 "Age in months (for children)"
label variable hml16a_32 "Age in months (for children)"
label variable hml16a_33 "Age in months (for children)"
label variable hml16a_34 "Age in months (for children)"
label variable hml16a_35 "Age in months (for children)"
label variable hml16a_36 "Age in months (for children)"
label variable hml17_01 "Flag for age from Individual file"
label variable hml17_02 "Flag for age from Individual file"
label variable hml17_03 "Flag for age from Individual file"
label variable hml17_04 "Flag for age from Individual file"
label variable hml17_05 "Flag for age from Individual file"
label variable hml17_06 "Flag for age from Individual file"
label variable hml17_07 "Flag for age from Individual file"
label variable hml17_08 "Flag for age from Individual file"
label variable hml17_09 "Flag for age from Individual file"
label variable hml17_10 "Flag for age from Individual file"
label variable hml17_11 "Flag for age from Individual file"
label variable hml17_12 "Flag for age from Individual file"
label variable hml17_13 "Flag for age from Individual file"
label variable hml17_14 "Flag for age from Individual file"
label variable hml17_15 "Flag for age from Individual file"
label variable hml17_16 "Flag for age from Individual file"
label variable hml17_17 "Flag for age from Individual file"
label variable hml17_18 "Flag for age from Individual file"
label variable hml17_19 "Flag for age from Individual file"
label variable hml17_20 "Flag for age from Individual file"
label variable hml17_21 "Flag for age from Individual file"
label variable hml17_22 "Flag for age from Individual file"
label variable hml17_23 "Flag for age from Individual file"
label variable hml17_24 "Flag for age from Individual file"
label variable hml17_25 "Flag for age from Individual file"
label variable hml17_26 "Flag for age from Individual file"
label variable hml17_27 "Flag for age from Individual file"
label variable hml17_28 "Flag for age from Individual file"
label variable hml17_29 "Flag for age from Individual file"
label variable hml17_30 "Flag for age from Individual file"
label variable hml17_31 "Flag for age from Individual file"
label variable hml17_32 "Flag for age from Individual file"
label variable hml17_33 "Flag for age from Individual file"
label variable hml17_34 "Flag for age from Individual file"
label variable hml17_35 "Flag for age from Individual file"
label variable hml17_36 "Flag for age from Individual file"
label variable hml18_01 "Pregnancy status from Individual file"
label variable hml18_02 "Pregnancy status from Individual file"
label variable hml18_03 "Pregnancy status from Individual file"
label variable hml18_04 "Pregnancy status from Individual file"
label variable hml18_05 "Pregnancy status from Individual file"
label variable hml18_06 "Pregnancy status from Individual file"
label variable hml18_07 "Pregnancy status from Individual file"
label variable hml18_08 "Pregnancy status from Individual file"
label variable hml18_09 "Pregnancy status from Individual file"
label variable hml18_10 "Pregnancy status from Individual file"
label variable hml18_11 "Pregnancy status from Individual file"
label variable hml18_12 "Pregnancy status from Individual file"
label variable hml18_13 "Pregnancy status from Individual file"
label variable hml18_14 "Pregnancy status from Individual file"
label variable hml18_15 "Pregnancy status from Individual file"
label variable hml18_16 "Pregnancy status from Individual file"
label variable hml18_17 "Pregnancy status from Individual file"
label variable hml18_18 "Pregnancy status from Individual file"
label variable hml18_19 "Pregnancy status from Individual file"
label variable hml18_20 "Pregnancy status from Individual file"
label variable hml18_21 "Pregnancy status from Individual file"
label variable hml18_22 "Pregnancy status from Individual file"
label variable hml18_23 "Pregnancy status from Individual file"
label variable hml18_24 "Pregnancy status from Individual file"
label variable hml18_25 "Pregnancy status from Individual file"
label variable hml18_26 "Pregnancy status from Individual file"
label variable hml18_27 "Pregnancy status from Individual file"
label variable hml18_28 "Pregnancy status from Individual file"
label variable hml18_29 "Pregnancy status from Individual file"
label variable hml18_30 "Pregnancy status from Individual file"
label variable hml18_31 "Pregnancy status from Individual file"
label variable hml18_32 "Pregnancy status from Individual file"
label variable hml18_33 "Pregnancy status from Individual file"
label variable hml18_34 "Pregnancy status from Individual file"
label variable hml18_35 "Pregnancy status from Individual file"
label variable hml18_36 "Pregnancy status from Individual file"
label variable hml19_01 "Person slept under an ever-treated net"
label variable hml19_02 "Person slept under an ever-treated net"
label variable hml19_03 "Person slept under an ever-treated net"
label variable hml19_04 "Person slept under an ever-treated net"
label variable hml19_05 "Person slept under an ever-treated net"
label variable hml19_06 "Person slept under an ever-treated net"
label variable hml19_07 "Person slept under an ever-treated net"
label variable hml19_08 "Person slept under an ever-treated net"
label variable hml19_09 "Person slept under an ever-treated net"
label variable hml19_10 "Person slept under an ever-treated net"
label variable hml19_11 "Person slept under an ever-treated net"
label variable hml19_12 "Person slept under an ever-treated net"
label variable hml19_13 "Person slept under an ever-treated net"
label variable hml19_14 "Person slept under an ever-treated net"
label variable hml19_15 "Person slept under an ever-treated net"
label variable hml19_16 "Person slept under an ever-treated net"
label variable hml19_17 "Person slept under an ever-treated net"
label variable hml19_18 "Person slept under an ever-treated net"
label variable hml19_19 "Person slept under an ever-treated net"
label variable hml19_20 "Person slept under an ever-treated net"
label variable hml19_21 "Person slept under an ever-treated net"
label variable hml19_22 "Person slept under an ever-treated net"
label variable hml19_23 "Person slept under an ever-treated net"
label variable hml19_24 "Person slept under an ever-treated net"
label variable hml19_25 "Person slept under an ever-treated net"
label variable hml19_26 "Person slept under an ever-treated net"
label variable hml19_27 "Person slept under an ever-treated net"
label variable hml19_28 "Person slept under an ever-treated net"
label variable hml19_29 "Person slept under an ever-treated net"
label variable hml19_30 "Person slept under an ever-treated net"
label variable hml19_31 "Person slept under an ever-treated net"
label variable hml19_32 "Person slept under an ever-treated net"
label variable hml19_33 "Person slept under an ever-treated net"
label variable hml19_34 "Person slept under an ever-treated net"
label variable hml19_35 "Person slept under an ever-treated net"
label variable hml19_36 "Person slept under an ever-treated net"
label variable hml20_01 "Person slept under an LLIN net"
label variable hml20_02 "Person slept under an LLIN net"
label variable hml20_03 "Person slept under an LLIN net"
label variable hml20_04 "Person slept under an LLIN net"
label variable hml20_05 "Person slept under an LLIN net"
label variable hml20_06 "Person slept under an LLIN net"
label variable hml20_07 "Person slept under an LLIN net"
label variable hml20_08 "Person slept under an LLIN net"
label variable hml20_09 "Person slept under an LLIN net"
label variable hml20_10 "Person slept under an LLIN net"
label variable hml20_11 "Person slept under an LLIN net"
label variable hml20_12 "Person slept under an LLIN net"
label variable hml20_13 "Person slept under an LLIN net"
label variable hml20_14 "Person slept under an LLIN net"
label variable hml20_15 "Person slept under an LLIN net"
label variable hml20_16 "Person slept under an LLIN net"
label variable hml20_17 "Person slept under an LLIN net"
label variable hml20_18 "Person slept under an LLIN net"
label variable hml20_19 "Person slept under an LLIN net"
label variable hml20_20 "Person slept under an LLIN net"
label variable hml20_21 "Person slept under an LLIN net"
label variable hml20_22 "Person slept under an LLIN net"
label variable hml20_23 "Person slept under an LLIN net"
label variable hml20_24 "Person slept under an LLIN net"
label variable hml20_25 "Person slept under an LLIN net"
label variable hml20_26 "Person slept under an LLIN net"
label variable hml20_27 "Person slept under an LLIN net"
label variable hml20_28 "Person slept under an LLIN net"
label variable hml20_29 "Person slept under an LLIN net"
label variable hml20_30 "Person slept under an LLIN net"
label variable hml20_31 "Person slept under an LLIN net"
label variable hml20_32 "Person slept under an LLIN net"
label variable hml20_33 "Person slept under an LLIN net"
label variable hml20_34 "Person slept under an LLIN net"
label variable hml20_35 "Person slept under an LLIN net"
label variable hml20_36 "Person slept under an LLIN net"
label variable hml30_01 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_02 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_03 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_04 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_05 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_06 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_07 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_08 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_09 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_10 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_11 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_12 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_13 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_14 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_15 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_16 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_17 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_18 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_19 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_20 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_21 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_22 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_23 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_24 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_25 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_26 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_27 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_28 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_29 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_30 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_31 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_32 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_33 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_34 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_35 "Line number of parent/caretaker (for malaria testing)"
label variable hml30_36 "Line number of parent/caretaker (for malaria testing)"
label variable hml31_01 "Read consent statement for malaria"
label variable hml31_02 "Read consent statement for malaria"
label variable hml31_03 "Read consent statement for malaria"
label variable hml31_04 "Read consent statement for malaria"
label variable hml31_05 "Read consent statement for malaria"
label variable hml31_06 "Read consent statement for malaria"
label variable hml31_07 "Read consent statement for malaria"
label variable hml31_08 "Read consent statement for malaria"
label variable hml31_09 "Read consent statement for malaria"
label variable hml31_10 "Read consent statement for malaria"
label variable hml31_11 "Read consent statement for malaria"
label variable hml31_12 "Read consent statement for malaria"
label variable hml31_13 "Read consent statement for malaria"
label variable hml31_14 "Read consent statement for malaria"
label variable hml31_15 "Read consent statement for malaria"
label variable hml31_16 "Read consent statement for malaria"
label variable hml31_17 "Read consent statement for malaria"
label variable hml31_18 "Read consent statement for malaria"
label variable hml31_19 "Read consent statement for malaria"
label variable hml31_20 "Read consent statement for malaria"
label variable hml31_21 "Read consent statement for malaria"
label variable hml31_22 "Read consent statement for malaria"
label variable hml31_23 "Read consent statement for malaria"
label variable hml31_24 "Read consent statement for malaria"
label variable hml31_25 "Read consent statement for malaria"
label variable hml31_26 "Read consent statement for malaria"
label variable hml31_27 "Read consent statement for malaria"
label variable hml31_28 "Read consent statement for malaria"
label variable hml31_29 "Read consent statement for malaria"
label variable hml31_30 "Read consent statement for malaria"
label variable hml31_31 "Read consent statement for malaria"
label variable hml31_32 "Read consent statement for malaria"
label variable hml31_33 "Read consent statement for malaria"
label variable hml31_34 "Read consent statement for malaria"
label variable hml31_35 "Read consent statement for malaria"
label variable hml31_36 "Read consent statement for malaria"
label variable hml32_01 "Final result of malaria from blood smear test"
label variable hml32_02 "Final result of malaria from blood smear test"
label variable hml32_03 "Final result of malaria from blood smear test"
label variable hml32_04 "Final result of malaria from blood smear test"
label variable hml32_05 "Final result of malaria from blood smear test"
label variable hml32_06 "Final result of malaria from blood smear test"
label variable hml32_07 "Final result of malaria from blood smear test"
label variable hml32_08 "Final result of malaria from blood smear test"
label variable hml32_09 "Final result of malaria from blood smear test"
label variable hml32_10 "Final result of malaria from blood smear test"
label variable hml32_11 "Final result of malaria from blood smear test"
label variable hml32_12 "Final result of malaria from blood smear test"
label variable hml32_13 "Final result of malaria from blood smear test"
label variable hml32_14 "Final result of malaria from blood smear test"
label variable hml32_15 "Final result of malaria from blood smear test"
label variable hml32_16 "Final result of malaria from blood smear test"
label variable hml32_17 "Final result of malaria from blood smear test"
label variable hml32_18 "Final result of malaria from blood smear test"
label variable hml32_19 "Final result of malaria from blood smear test"
label variable hml32_20 "Final result of malaria from blood smear test"
label variable hml32_21 "Final result of malaria from blood smear test"
label variable hml32_22 "Final result of malaria from blood smear test"
label variable hml32_23 "Final result of malaria from blood smear test"
label variable hml32_24 "Final result of malaria from blood smear test"
label variable hml32_25 "Final result of malaria from blood smear test"
label variable hml32_26 "Final result of malaria from blood smear test"
label variable hml32_27 "Final result of malaria from blood smear test"
label variable hml32_28 "Final result of malaria from blood smear test"
label variable hml32_29 "Final result of malaria from blood smear test"
label variable hml32_30 "Final result of malaria from blood smear test"
label variable hml32_31 "Final result of malaria from blood smear test"
label variable hml32_32 "Final result of malaria from blood smear test"
label variable hml32_33 "Final result of malaria from blood smear test"
label variable hml32_34 "Final result of malaria from blood smear test"
label variable hml32_35 "Final result of malaria from blood smear test"
label variable hml32_36 "Final result of malaria from blood smear test"
label variable hml32a_01 "Presence of species: falciparum (Pf)"
label variable hml32a_02 "Presence of species: falciparum (Pf)"
label variable hml32a_03 "Presence of species: falciparum (Pf)"
label variable hml32a_04 "Presence of species: falciparum (Pf)"
label variable hml32a_05 "Presence of species: falciparum (Pf)"
label variable hml32a_06 "Presence of species: falciparum (Pf)"
label variable hml32a_07 "Presence of species: falciparum (Pf)"
label variable hml32a_08 "Presence of species: falciparum (Pf)"
label variable hml32a_09 "Presence of species: falciparum (Pf)"
label variable hml32a_10 "Presence of species: falciparum (Pf)"
label variable hml32a_11 "Presence of species: falciparum (Pf)"
label variable hml32a_12 "Presence of species: falciparum (Pf)"
label variable hml32a_13 "Presence of species: falciparum (Pf)"
label variable hml32a_14 "Presence of species: falciparum (Pf)"
label variable hml32a_15 "Presence of species: falciparum (Pf)"
label variable hml32a_16 "Presence of species: falciparum (Pf)"
label variable hml32a_17 "Presence of species: falciparum (Pf)"
label variable hml32a_18 "Presence of species: falciparum (Pf)"
label variable hml32a_19 "Presence of species: falciparum (Pf)"
label variable hml32a_20 "Presence of species: falciparum (Pf)"
label variable hml32a_21 "Presence of species: falciparum (Pf)"
label variable hml32a_22 "Presence of species: falciparum (Pf)"
label variable hml32a_23 "Presence of species: falciparum (Pf)"
label variable hml32a_24 "Presence of species: falciparum (Pf)"
label variable hml32a_25 "Presence of species: falciparum (Pf)"
label variable hml32a_26 "Presence of species: falciparum (Pf)"
label variable hml32a_27 "Presence of species: falciparum (Pf)"
label variable hml32a_28 "Presence of species: falciparum (Pf)"
label variable hml32a_29 "Presence of species: falciparum (Pf)"
label variable hml32a_30 "Presence of species: falciparum (Pf)"
label variable hml32a_31 "Presence of species: falciparum (Pf)"
label variable hml32a_32 "Presence of species: falciparum (Pf)"
label variable hml32a_33 "Presence of species: falciparum (Pf)"
label variable hml32a_34 "Presence of species: falciparum (Pf)"
label variable hml32a_35 "Presence of species: falciparum (Pf)"
label variable hml32a_36 "Presence of species: falciparum (Pf)"
label variable hml32b_01 "Presence of species: malariae (Pm)"
label variable hml32b_02 "Presence of species: malariae (Pm)"
label variable hml32b_03 "Presence of species: malariae (Pm)"
label variable hml32b_04 "Presence of species: malariae (Pm)"
label variable hml32b_05 "Presence of species: malariae (Pm)"
label variable hml32b_06 "Presence of species: malariae (Pm)"
label variable hml32b_07 "Presence of species: malariae (Pm)"
label variable hml32b_08 "Presence of species: malariae (Pm)"
label variable hml32b_09 "Presence of species: malariae (Pm)"
label variable hml32b_10 "Presence of species: malariae (Pm)"
label variable hml32b_11 "Presence of species: malariae (Pm)"
label variable hml32b_12 "Presence of species: malariae (Pm)"
label variable hml32b_13 "Presence of species: malariae (Pm)"
label variable hml32b_14 "Presence of species: malariae (Pm)"
label variable hml32b_15 "Presence of species: malariae (Pm)"
label variable hml32b_16 "Presence of species: malariae (Pm)"
label variable hml32b_17 "Presence of species: malariae (Pm)"
label variable hml32b_18 "Presence of species: malariae (Pm)"
label variable hml32b_19 "Presence of species: malariae (Pm)"
label variable hml32b_20 "Presence of species: malariae (Pm)"
label variable hml32b_21 "Presence of species: malariae (Pm)"
label variable hml32b_22 "Presence of species: malariae (Pm)"
label variable hml32b_23 "Presence of species: malariae (Pm)"
label variable hml32b_24 "Presence of species: malariae (Pm)"
label variable hml32b_25 "Presence of species: malariae (Pm)"
label variable hml32b_26 "Presence of species: malariae (Pm)"
label variable hml32b_27 "Presence of species: malariae (Pm)"
label variable hml32b_28 "Presence of species: malariae (Pm)"
label variable hml32b_29 "Presence of species: malariae (Pm)"
label variable hml32b_30 "Presence of species: malariae (Pm)"
label variable hml32b_31 "Presence of species: malariae (Pm)"
label variable hml32b_32 "Presence of species: malariae (Pm)"
label variable hml32b_33 "Presence of species: malariae (Pm)"
label variable hml32b_34 "Presence of species: malariae (Pm)"
label variable hml32b_35 "Presence of species: malariae (Pm)"
label variable hml32b_36 "Presence of species: malariae (Pm)"
label variable hml32c_01 "Presence of species: ovale (Po)"
label variable hml32c_02 "Presence of species: ovale (Po)"
label variable hml32c_03 "Presence of species: ovale (Po)"
label variable hml32c_04 "Presence of species: ovale (Po)"
label variable hml32c_05 "Presence of species: ovale (Po)"
label variable hml32c_06 "Presence of species: ovale (Po)"
label variable hml32c_07 "Presence of species: ovale (Po)"
label variable hml32c_08 "Presence of species: ovale (Po)"
label variable hml32c_09 "Presence of species: ovale (Po)"
label variable hml32c_10 "Presence of species: ovale (Po)"
label variable hml32c_11 "Presence of species: ovale (Po)"
label variable hml32c_12 "Presence of species: ovale (Po)"
label variable hml32c_13 "Presence of species: ovale (Po)"
label variable hml32c_14 "Presence of species: ovale (Po)"
label variable hml32c_15 "Presence of species: ovale (Po)"
label variable hml32c_16 "Presence of species: ovale (Po)"
label variable hml32c_17 "Presence of species: ovale (Po)"
label variable hml32c_18 "Presence of species: ovale (Po)"
label variable hml32c_19 "Presence of species: ovale (Po)"
label variable hml32c_20 "Presence of species: ovale (Po)"
label variable hml32c_21 "Presence of species: ovale (Po)"
label variable hml32c_22 "Presence of species: ovale (Po)"
label variable hml32c_23 "Presence of species: ovale (Po)"
label variable hml32c_24 "Presence of species: ovale (Po)"
label variable hml32c_25 "Presence of species: ovale (Po)"
label variable hml32c_26 "Presence of species: ovale (Po)"
label variable hml32c_27 "Presence of species: ovale (Po)"
label variable hml32c_28 "Presence of species: ovale (Po)"
label variable hml32c_29 "Presence of species: ovale (Po)"
label variable hml32c_30 "Presence of species: ovale (Po)"
label variable hml32c_31 "Presence of species: ovale (Po)"
label variable hml32c_32 "Presence of species: ovale (Po)"
label variable hml32c_33 "Presence of species: ovale (Po)"
label variable hml32c_34 "Presence of species: ovale (Po)"
label variable hml32c_35 "Presence of species: ovale (Po)"
label variable hml32c_36 "Presence of species: ovale (Po)"
label variable hml32d_01 "Presence of species: vivax (Pv)"
label variable hml32d_02 "Presence of species: vivax (Pv)"
label variable hml32d_03 "Presence of species: vivax (Pv)"
label variable hml32d_04 "Presence of species: vivax (Pv)"
label variable hml32d_05 "Presence of species: vivax (Pv)"
label variable hml32d_06 "Presence of species: vivax (Pv)"
label variable hml32d_07 "Presence of species: vivax (Pv)"
label variable hml32d_08 "Presence of species: vivax (Pv)"
label variable hml32d_09 "Presence of species: vivax (Pv)"
label variable hml32d_10 "Presence of species: vivax (Pv)"
label variable hml32d_11 "Presence of species: vivax (Pv)"
label variable hml32d_12 "Presence of species: vivax (Pv)"
label variable hml32d_13 "Presence of species: vivax (Pv)"
label variable hml32d_14 "Presence of species: vivax (Pv)"
label variable hml32d_15 "Presence of species: vivax (Pv)"
label variable hml32d_16 "Presence of species: vivax (Pv)"
label variable hml32d_17 "Presence of species: vivax (Pv)"
label variable hml32d_18 "Presence of species: vivax (Pv)"
label variable hml32d_19 "Presence of species: vivax (Pv)"
label variable hml32d_20 "Presence of species: vivax (Pv)"
label variable hml32d_21 "Presence of species: vivax (Pv)"
label variable hml32d_22 "Presence of species: vivax (Pv)"
label variable hml32d_23 "Presence of species: vivax (Pv)"
label variable hml32d_24 "Presence of species: vivax (Pv)"
label variable hml32d_25 "Presence of species: vivax (Pv)"
label variable hml32d_26 "Presence of species: vivax (Pv)"
label variable hml32d_27 "Presence of species: vivax (Pv)"
label variable hml32d_28 "Presence of species: vivax (Pv)"
label variable hml32d_29 "Presence of species: vivax (Pv)"
label variable hml32d_30 "Presence of species: vivax (Pv)"
label variable hml32d_31 "Presence of species: vivax (Pv)"
label variable hml32d_32 "Presence of species: vivax (Pv)"
label variable hml32d_33 "Presence of species: vivax (Pv)"
label variable hml32d_34 "Presence of species: vivax (Pv)"
label variable hml32d_35 "Presence of species: vivax (Pv)"
label variable hml32d_36 "Presence of species: vivax (Pv)"
label variable hml32e_01 "NA - Presence of species: CS"
label variable hml32e_02 "NA - Presence of species: CS"
label variable hml32e_03 "NA - Presence of species: CS"
label variable hml32e_04 "NA - Presence of species: CS"
label variable hml32e_05 "NA - Presence of species: CS"
label variable hml32e_06 "NA - Presence of species: CS"
label variable hml32e_07 "NA - Presence of species: CS"
label variable hml32e_08 "NA - Presence of species: CS"
label variable hml32e_09 "NA - Presence of species: CS"
label variable hml32e_10 "NA - Presence of species: CS"
label variable hml32e_11 "NA - Presence of species: CS"
label variable hml32e_12 "NA - Presence of species: CS"
label variable hml32e_13 "NA - Presence of species: CS"
label variable hml32e_14 "NA - Presence of species: CS"
label variable hml32e_15 "NA - Presence of species: CS"
label variable hml32e_16 "NA - Presence of species: CS"
label variable hml32e_17 "NA - Presence of species: CS"
label variable hml32e_18 "NA - Presence of species: CS"
label variable hml32e_19 "NA - Presence of species: CS"
label variable hml32e_20 "NA - Presence of species: CS"
label variable hml32e_21 "NA - Presence of species: CS"
label variable hml32e_22 "NA - Presence of species: CS"
label variable hml32e_23 "NA - Presence of species: CS"
label variable hml32e_24 "NA - Presence of species: CS"
label variable hml32e_25 "NA - Presence of species: CS"
label variable hml32e_26 "NA - Presence of species: CS"
label variable hml32e_27 "NA - Presence of species: CS"
label variable hml32e_28 "NA - Presence of species: CS"
label variable hml32e_29 "NA - Presence of species: CS"
label variable hml32e_30 "NA - Presence of species: CS"
label variable hml32e_31 "NA - Presence of species: CS"
label variable hml32e_32 "NA - Presence of species: CS"
label variable hml32e_33 "NA - Presence of species: CS"
label variable hml32e_34 "NA - Presence of species: CS"
label variable hml32e_35 "NA - Presence of species: CS"
label variable hml32e_36 "NA - Presence of species: CS"
label variable hml32f_01 "NA - Presence of species: CS"
label variable hml32f_02 "NA - Presence of species: CS"
label variable hml32f_03 "NA - Presence of species: CS"
label variable hml32f_04 "NA - Presence of species: CS"
label variable hml32f_05 "NA - Presence of species: CS"
label variable hml32f_06 "NA - Presence of species: CS"
label variable hml32f_07 "NA - Presence of species: CS"
label variable hml32f_08 "NA - Presence of species: CS"
label variable hml32f_09 "NA - Presence of species: CS"
label variable hml32f_10 "NA - Presence of species: CS"
label variable hml32f_11 "NA - Presence of species: CS"
label variable hml32f_12 "NA - Presence of species: CS"
label variable hml32f_13 "NA - Presence of species: CS"
label variable hml32f_14 "NA - Presence of species: CS"
label variable hml32f_15 "NA - Presence of species: CS"
label variable hml32f_16 "NA - Presence of species: CS"
label variable hml32f_17 "NA - Presence of species: CS"
label variable hml32f_18 "NA - Presence of species: CS"
label variable hml32f_19 "NA - Presence of species: CS"
label variable hml32f_20 "NA - Presence of species: CS"
label variable hml32f_21 "NA - Presence of species: CS"
label variable hml32f_22 "NA - Presence of species: CS"
label variable hml32f_23 "NA - Presence of species: CS"
label variable hml32f_24 "NA - Presence of species: CS"
label variable hml32f_25 "NA - Presence of species: CS"
label variable hml32f_26 "NA - Presence of species: CS"
label variable hml32f_27 "NA - Presence of species: CS"
label variable hml32f_28 "NA - Presence of species: CS"
label variable hml32f_29 "NA - Presence of species: CS"
label variable hml32f_30 "NA - Presence of species: CS"
label variable hml32f_31 "NA - Presence of species: CS"
label variable hml32f_32 "NA - Presence of species: CS"
label variable hml32f_33 "NA - Presence of species: CS"
label variable hml32f_34 "NA - Presence of species: CS"
label variable hml32f_35 "NA - Presence of species: CS"
label variable hml32f_36 "NA - Presence of species: CS"
label variable hml32g_01 "NA - Presence of species: CS"
label variable hml32g_02 "NA - Presence of species: CS"
label variable hml32g_03 "NA - Presence of species: CS"
label variable hml32g_04 "NA - Presence of species: CS"
label variable hml32g_05 "NA - Presence of species: CS"
label variable hml32g_06 "NA - Presence of species: CS"
label variable hml32g_07 "NA - Presence of species: CS"
label variable hml32g_08 "NA - Presence of species: CS"
label variable hml32g_09 "NA - Presence of species: CS"
label variable hml32g_10 "NA - Presence of species: CS"
label variable hml32g_11 "NA - Presence of species: CS"
label variable hml32g_12 "NA - Presence of species: CS"
label variable hml32g_13 "NA - Presence of species: CS"
label variable hml32g_14 "NA - Presence of species: CS"
label variable hml32g_15 "NA - Presence of species: CS"
label variable hml32g_16 "NA - Presence of species: CS"
label variable hml32g_17 "NA - Presence of species: CS"
label variable hml32g_18 "NA - Presence of species: CS"
label variable hml32g_19 "NA - Presence of species: CS"
label variable hml32g_20 "NA - Presence of species: CS"
label variable hml32g_21 "NA - Presence of species: CS"
label variable hml32g_22 "NA - Presence of species: CS"
label variable hml32g_23 "NA - Presence of species: CS"
label variable hml32g_24 "NA - Presence of species: CS"
label variable hml32g_25 "NA - Presence of species: CS"
label variable hml32g_26 "NA - Presence of species: CS"
label variable hml32g_27 "NA - Presence of species: CS"
label variable hml32g_28 "NA - Presence of species: CS"
label variable hml32g_29 "NA - Presence of species: CS"
label variable hml32g_30 "NA - Presence of species: CS"
label variable hml32g_31 "NA - Presence of species: CS"
label variable hml32g_32 "NA - Presence of species: CS"
label variable hml32g_33 "NA - Presence of species: CS"
label variable hml32g_34 "NA - Presence of species: CS"
label variable hml32g_35 "NA - Presence of species: CS"
label variable hml32g_36 "NA - Presence of species: CS"
label variable hml33_01 "Result of malaria measurement"
label variable hml33_02 "Result of malaria measurement"
label variable hml33_03 "Result of malaria measurement"
label variable hml33_04 "Result of malaria measurement"
label variable hml33_05 "Result of malaria measurement"
label variable hml33_06 "Result of malaria measurement"
label variable hml33_07 "Result of malaria measurement"
label variable hml33_08 "Result of malaria measurement"
label variable hml33_09 "Result of malaria measurement"
label variable hml33_10 "Result of malaria measurement"
label variable hml33_11 "Result of malaria measurement"
label variable hml33_12 "Result of malaria measurement"
label variable hml33_13 "Result of malaria measurement"
label variable hml33_14 "Result of malaria measurement"
label variable hml33_15 "Result of malaria measurement"
label variable hml33_16 "Result of malaria measurement"
label variable hml33_17 "Result of malaria measurement"
label variable hml33_18 "Result of malaria measurement"
label variable hml33_19 "Result of malaria measurement"
label variable hml33_20 "Result of malaria measurement"
label variable hml33_21 "Result of malaria measurement"
label variable hml33_22 "Result of malaria measurement"
label variable hml33_23 "Result of malaria measurement"
label variable hml33_24 "Result of malaria measurement"
label variable hml33_25 "Result of malaria measurement"
label variable hml33_26 "Result of malaria measurement"
label variable hml33_27 "Result of malaria measurement"
label variable hml33_28 "Result of malaria measurement"
label variable hml33_29 "Result of malaria measurement"
label variable hml33_30 "Result of malaria measurement"
label variable hml33_31 "Result of malaria measurement"
label variable hml33_32 "Result of malaria measurement"
label variable hml33_33 "Result of malaria measurement"
label variable hml33_34 "Result of malaria measurement"
label variable hml33_35 "Result of malaria measurement"
label variable hml33_36 "Result of malaria measurement"
label variable hml34_01 "Bar code for blood smear sample"
label variable hml34_02 "Bar code for blood smear sample"
label variable hml34_03 "Bar code for blood smear sample"
label variable hml34_04 "Bar code for blood smear sample"
label variable hml34_05 "Bar code for blood smear sample"
label variable hml34_06 "Bar code for blood smear sample"
label variable hml34_07 "Bar code for blood smear sample"
label variable hml34_08 "Bar code for blood smear sample"
label variable hml34_09 "Bar code for blood smear sample"
label variable hml34_10 "Bar code for blood smear sample"
label variable hml34_11 "Bar code for blood smear sample"
label variable hml34_12 "Bar code for blood smear sample"
label variable hml34_13 "Bar code for blood smear sample"
label variable hml34_14 "Bar code for blood smear sample"
label variable hml34_15 "Bar code for blood smear sample"
label variable hml34_16 "Bar code for blood smear sample"
label variable hml34_17 "Bar code for blood smear sample"
label variable hml34_18 "Bar code for blood smear sample"
label variable hml34_19 "Bar code for blood smear sample"
label variable hml34_20 "Bar code for blood smear sample"
label variable hml34_21 "Bar code for blood smear sample"
label variable hml34_22 "Bar code for blood smear sample"
label variable hml34_23 "Bar code for blood smear sample"
label variable hml34_24 "Bar code for blood smear sample"
label variable hml34_25 "Bar code for blood smear sample"
label variable hml34_26 "Bar code for blood smear sample"
label variable hml34_27 "Bar code for blood smear sample"
label variable hml34_28 "Bar code for blood smear sample"
label variable hml34_29 "Bar code for blood smear sample"
label variable hml34_30 "Bar code for blood smear sample"
label variable hml34_31 "Bar code for blood smear sample"
label variable hml34_32 "Bar code for blood smear sample"
label variable hml34_33 "Bar code for blood smear sample"
label variable hml34_34 "Bar code for blood smear sample"
label variable hml34_35 "Bar code for blood smear sample"
label variable hml34_36 "Bar code for blood smear sample"
label variable hml35_01 "Result of malaria rapid test"
label variable hml35_02 "Result of malaria rapid test"
label variable hml35_03 "Result of malaria rapid test"
label variable hml35_04 "Result of malaria rapid test"
label variable hml35_05 "Result of malaria rapid test"
label variable hml35_06 "Result of malaria rapid test"
label variable hml35_07 "Result of malaria rapid test"
label variable hml35_08 "Result of malaria rapid test"
label variable hml35_09 "Result of malaria rapid test"
label variable hml35_10 "Result of malaria rapid test"
label variable hml35_11 "Result of malaria rapid test"
label variable hml35_12 "Result of malaria rapid test"
label variable hml35_13 "Result of malaria rapid test"
label variable hml35_14 "Result of malaria rapid test"
label variable hml35_15 "Result of malaria rapid test"
label variable hml35_16 "Result of malaria rapid test"
label variable hml35_17 "Result of malaria rapid test"
label variable hml35_18 "Result of malaria rapid test"
label variable hml35_19 "Result of malaria rapid test"
label variable hml35_20 "Result of malaria rapid test"
label variable hml35_21 "Result of malaria rapid test"
label variable hml35_22 "Result of malaria rapid test"
label variable hml35_23 "Result of malaria rapid test"
label variable hml35_24 "Result of malaria rapid test"
label variable hml35_25 "Result of malaria rapid test"
label variable hml35_26 "Result of malaria rapid test"
label variable hml35_27 "Result of malaria rapid test"
label variable hml35_28 "Result of malaria rapid test"
label variable hml35_29 "Result of malaria rapid test"
label variable hml35_30 "Result of malaria rapid test"
label variable hml35_31 "Result of malaria rapid test"
label variable hml35_32 "Result of malaria rapid test"
label variable hml35_33 "Result of malaria rapid test"
label variable hml35_34 "Result of malaria rapid test"
label variable hml35_35 "Result of malaria rapid test"
label variable hml35_36 "Result of malaria rapid test"
label variable hml36_01 "Fieldworker measurer code for malaria"
label variable hml36_02 "Fieldworker measurer code for malaria"
label variable hml36_03 "Fieldworker measurer code for malaria"
label variable hml36_04 "Fieldworker measurer code for malaria"
label variable hml36_05 "Fieldworker measurer code for malaria"
label variable hml36_06 "Fieldworker measurer code for malaria"
label variable hml36_07 "Fieldworker measurer code for malaria"
label variable hml36_08 "Fieldworker measurer code for malaria"
label variable hml36_09 "Fieldworker measurer code for malaria"
label variable hml36_10 "Fieldworker measurer code for malaria"
label variable hml36_11 "Fieldworker measurer code for malaria"
label variable hml36_12 "Fieldworker measurer code for malaria"
label variable hml36_13 "Fieldworker measurer code for malaria"
label variable hml36_14 "Fieldworker measurer code for malaria"
label variable hml36_15 "Fieldworker measurer code for malaria"
label variable hml36_16 "Fieldworker measurer code for malaria"
label variable hml36_17 "Fieldworker measurer code for malaria"
label variable hml36_18 "Fieldworker measurer code for malaria"
label variable hml36_19 "Fieldworker measurer code for malaria"
label variable hml36_20 "Fieldworker measurer code for malaria"
label variable hml36_21 "Fieldworker measurer code for malaria"
label variable hml36_22 "Fieldworker measurer code for malaria"
label variable hml36_23 "Fieldworker measurer code for malaria"
label variable hml36_24 "Fieldworker measurer code for malaria"
label variable hml36_25 "Fieldworker measurer code for malaria"
label variable hml36_26 "Fieldworker measurer code for malaria"
label variable hml36_27 "Fieldworker measurer code for malaria"
label variable hml36_28 "Fieldworker measurer code for malaria"
label variable hml36_29 "Fieldworker measurer code for malaria"
label variable hml36_30 "Fieldworker measurer code for malaria"
label variable hml36_31 "Fieldworker measurer code for malaria"
label variable hml36_32 "Fieldworker measurer code for malaria"
label variable hml36_33 "Fieldworker measurer code for malaria"
label variable hml36_34 "Fieldworker measurer code for malaria"
label variable hml36_35 "Fieldworker measurer code for malaria"
label variable hml36_36 "Fieldworker measurer code for malaria"

#delimit ;
label define HV003   
     0 "Incomplete household"
;
label define HV015   
     1 "Completed"
     2 "No Household member/no competent member at home"
     3 "Entire Household absent for extended period of time"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant or address not a dwelling"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV017   
     9 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV022   
     1 "Kampala"
     2 "South Buganda"
     3 "North Buganda"
     4 "Busoga"
     5 "Bukedi"
     6 "Bugisu"
     7 "Teso"
     8 "Karamoja"
     9 "Lango"
    10 "Acholi"
    11 "West Nile"
    12 "Bunyoro"
    13 "Tooro"
    14 "Ankole"
    15 "Kigezi"
    16 "Refugee settlements"
;
label define HV023   
     1 "Kampala"
     2 "South Buganda"
     3 "North Buganda"
     4 "Busoga"
     5 "Bukedi"
     6 "Bugisu"
     7 "Teso"
     8 "Karamoja"
     9 "Lango"
    10 "Acholi"
    11 "West Nile"
    12 "Bunyoro"
    13 "Tooro"
    14 "Ankole"
    15 "Kigezi"
    16 "Refugee settlements"
;
label define HV024   
     1 "Kampala"
     2 "South Buganda"
     3 "North Buganda"
     4 "Busoga"
     5 "Bukedi"
     6 "Bugisu"
     7 "Teso"
     8 "Karamoja"
     9 "Lango"
    10 "Acholi"
    11 "West Nile"
    12 "Bunyoro"
    13 "Tooro"
    14 "Ankole"
    15 "Kigezi"
;
label define HV025   
     1 "Urban"
     2 "Rural"
     3 "Refugee"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV040   
  9999 "Missing"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV045A  
     1 "English"
     2 "Luganda"
     3 "Luo"
     4 "Lugbara"
     5 "Ateso"
     6 "Runyankole/Rukiga"
     7 "Runyoro/Rutoro"
    96 "Other"
;
label define HV045B  
     1 "English"
     2 "Luganda"
     3 "Luo"
     4 "Lugbara"
     5 "Ateso"
     6 "Runyankole/Rukiga"
     7 "Runyoro/Rutoro"
    96 "Other"
;
label define HV045C  
     1 "English"
     2 "Luganda"
     3 "Luo"
     4 "Lugbara"
     5 "Ateso"
     6 "Runyankole/Rukiga"
     7 "Runyoro/Rutoro"
    96 "Other"
;
label define HV046   
     0 "No"
     1 "Yes"
;
label define HV801   
  9999 "Missing"
;
label define HV802   
  9999 "Missing"
;
label define HV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define HV804   
     9 "Missing"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    63 "Bicycle with jerrycans"
    71 "Bottled water"
    72 "Sachet water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped to yard/plot"
    13 "Piped to neighbor"
    14 "Public tap/standpipe"
    20 "TUBE WELL WATER"
    21 "Tube well or borehole"
    30 "DUG WELL (OPEN/PROTECTED)"
    31 "Protected well"
    32 "Unprotected well"
    40 "SURFACE FROM SPRING"
    41 "Protected spring"
    42 "Unprotected spring"
    43 "River/dam/lake/ponds/stream/canal/irrigation channel"
    51 "Rainwater"
    61 "Tanker truck"
    62 "Cart with small tank"
    63 "Bicycle with jerrycans"
    71 "Bottled water"
    96 "Other"
;
label define HV201A  
     0 "No, not interrupted for a full day"
     1 "Yes, interrupted for a full day or more"
     8 "Don't know"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to pit latrine"
    14 "Flush to somewhere else"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated Improved Pit latrine (VIP)"
    22 "Pit latrine with slab"
    23 "Pit latrine without slab/open pit"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    41 "Composting toilet"
    42 "Bucket toilet"
    43 "Hanging toilet/latrine"
    96 "Other"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth/sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Concrete"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    36 "Stones"
    37 "Bricks"
    96 "Other"
;
label define HV214   
    10 "NATURAL"
    11 "No walls"
    12 "Thatched/straw"
    13 "Dirt"
    20 "RUDIMENTARY"
    21 "Poles with mud"
    22 "Stone with mud"
    23 "Unburnt bricks with mud"
    24 "Plywood"
    25 "Cardboard"
    26 "Reused wood"
    27 "Unburnt bricks with plaster"
    28 "Burnt bricks with mud"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Burnt bricks with cement"
    34 "Cement blocks"
    35 "Unburnt bricks with cement"
    36 "Wood planks/shingles"
    96 "Other"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch/palm leaf"
    13 "Mud"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    22 "Tins"
    23 "Wood planks"
    24 "Cardboard"
    25 "Tarpaulin"
    30 "FINISHED"
    31 "Iron sheets"
    32 "Wood"
    33 "Asbestos"
    34 "Tiles"
    35 "Concrete"
    36 "Roofing shingles"
    96 "Other"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opposite sex"
     3 "Two adults, same sex"
     4 "Three+ related adults"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "Don't know"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG/Cylinder gas"
     3 "Natural gas"
     4 "Biogas"
     5 "Kerosene"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Agricultural crop"
    11 "Animal dung"
    95 "No food cooked in house"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No net in household"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV243E  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
   950 "95 or more"
   998 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246B  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246C  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246H  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246I  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246J  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV246K  
     0 "None"
    95 "95 or more"
    98 "Unknown"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV253   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253H  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253X  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV253Z  
     0 "No"
     1 "Yes: don't know who sprayed the dwelling"
     8 "Don't know if it was sprayed"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HV270A  
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHDISTRICT
   101 "Kalangala"
   102 "Kampala"
   103 "Kiboga"
   104 "Luwero"
   105 "Masaka"
   106 "Mpigi"
   107 "Mubende"
   108 "Mukono"
   109 "Nakasongola"
   110 "Rakai"
   111 "Ssembabule"
   112 "Kayunga"
   113 "Wakiso"
   115 "Mityana"
   116 "Nakaseke"
   117 "Buikwe"
   120 "Buvuma"
   121 "Gomba"
   122 "Kalungu"
   123 "Kyankwanzi"
   124 "Lwengo"
   125 "Kyotera"
   126 "Kassanda"
   201 "Bugiri"
   202 "Busia"
   203 "Iganga"
   204 "Jinja"
   205 "Kamuli"
   206 "Kapchorwa"
   207 "Katakwi"
   208 "Kumi"
   209 "Mbale"
   210 "Pallisa"
   211 "Soroti"
   212 "Tororo"
   213 "Kaberamaido"
   214 "Mayuge"
   215 "Sironko"
   216 "Amuria"
   217 "Budaka"
   218 "Bududa"
   219 "Bukedea"
   220 "Bukwo"
   221 "Butaleja"
   222 "Kaliro"
   223 "Manafwa"
   224 "Namutumba"
   225 "Bulambuli"
   226 "Buyende"
   227 "Kibuku"
   228 "Kween"
   229 "Luuka"
   230 "Namayingo"
   231 "Ngora"
   232 "Serere"
   233 "Butebo"
   234 "Namisindwa"
   235 "Bugweri"
   236 "Kapelebyong"
   301 "Adjumani"
   302 "Apac"
   303 "Arua"
   304 "Gulu"
   305 "Kitgum"
   306 "Kotido"
   307 "Lira"
   308 "Moroto"
   309 "Moyo"
   310 "Nebbi"
   311 "Nakapiripirit"
   312 "Pader"
   313 "Yumbe"
   314 "Abim"
   315 "Amolatar"
   316 "Amuru"
   317 "Dokolo"
   318 "Kaabong"
   319 "Koboko"
   320 "Maracha"
   321 "Oyam"
   322 "Agago"
   323 "Alebtong"
   324 "Amudat"
   325 "Kole"
   326 "Lamwo"
   327 "Napak"
   328 "Nwoya"
   329 "Otuke"
   330 "Zombo"
   331 "Omoro"
   332 "Pakwach"
   333 "Kwania"
   334 "Nabilatuk"
   401 "Bundibugyo"
   402 "Bushenyi"
   403 "Hoima"
   404 "Kabale"
   405 "Kabarole"
   406 "Kasese"
   407 "Kibaale"
   408 "Kisoro"
   409 "Masindi"
   410 "Mbarara"
   411 "Ntungamo"
   412 "Rukungiri"
   413 "Kamwenge"
   414 "Kanungu"
   415 "Kyenjojo"
   416 "Buliisa"
   417 "Ibanda"
   418 "Isingiro"
   419 "Kiruhura"
   421 "Kiryandongo"
   422 "Kyegegwa"
   423 "Mitooma"
   424 "Ntoroko"
   426 "Sheema"
   427 "Kagadi"
   428 "Kakumiro"
   429 "Rubanda"
   430 "Rukiga"
   431 "Bunyangabu"
   432 "Kikuube"
;
label define SHREFUGEE
     0 "Not in refugee settlement"
     1 "Refugee settlement"
;
label define SH114G  
     0 "No"
     1 "Yes"
;
label define SH114H  
     0 "No"
     1 "Yes"
;
label define SH114I  
     0 "No"
     1 "Yes"
;
label define SH114J  
     0 "No"
     1 "Yes"
;
label define SH114K  
     0 "No"
     1 "Yes"
;
label define SH114L  
     0 "No"
     1 "Yes"
;
label define SH114M  
     0 "No"
     1 "Yes"
;
label define SH115H  
     0 "No"
     1 "Yes"
;
label define SH117A  
     0 "Less than 1 month ago"
;
label define SH117C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH118   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SH118A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster/stepchild"
    12 "Not related"
    13 "Niece/nephew by blood"
    14 "Niece/nephew by marriage"
    98 "Don't know"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    95 "95+"
    98 "Don't know"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HC16    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "Don't know"
;
label define HC31    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define HC33    
     0 "Month, year and day"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
     3 "Not present/other"
;
label define HC53    
   994 "Not present"
   995 "Refused"
   996 "Other"
;
label define HC55    
     0 "Measured"
     3 "Not present/other"
     4 "Refused"
     6 "Other"
;
label define HC56    
   997 "Inconsistent"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     0 "No"
     1 "Yes"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC62    
    98 "Don't know"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "'O' level"
     3 "'A' level"
     4 "Tertiary"
     5 "University"
     8 "Don't know"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define SB118A  
     0 "No"
     1 "Yes"
;
label define SB118B  
     0 "No"
     1 "Yes"
;
label define SB118C  
     0 "No"
     1 "Yes"
;
label define SB118D  
     0 "No"
     1 "Yes"
;
label define SB118E  
     0 "No"
     1 "Yes"
;
label define SB118F  
     0 "No"
     1 "Yes"
;
label define SB118G  
     0 "No"
     1 "Yes"
;
label define SB118H  
     0 "No"
     1 "Yes"
;
label define SB121   
     0 "No"
     1 "Yes"
;
label define SB125   
     1 "Accepted"
     5 "Refused"
     6 "Other"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent treatment"
     2 "Pretreated, requiring future treatment"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     8 "Don't know"
;
label define HML7    
    10 "Long-lasting insecticide treated nets (LLIN)"
    11 "LLIN - Permanet 2.0"
    12 "LLIN - Permanet 3.0"
    13 "LLIN - Duranet"
    14 "LLIN - Interceptor"
    15 "LLIN - Netprotect"
    16 "LLIN - Olyset"
    17 "LLIN - Olyset plus"
    18 "LLIN - Dawa plus"
    19 "LLIN - Iconlife"
    20 "LLIN - Yorkool"
    21 "LLIN - Magnet"
    22 "LLIN - Other"
    23 "LLIN - Don't know brand"
    96 "Other brand"
    98 "Dont' know brand"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent/LLIN net"
     8 "Not sure"
;
label define HML9    
    95 "25+ months ago"
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "Not sure (DK)"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define HML22   
     0 "No"
     1 "Yes, campaign"
     2 "Yes, antenatal care"
     3 "Yes, immunization visit"
;
label define HML23   
    10 "Government health facility"
    11 "Government hospital"
    12 "Government health facility"
    20 "Private health facility"
    21 "Private hospital/clinic"
    30 "Other sources"
    31 "Pharmacy"
    32 "Shop/market"
    33 "CHW"
    34 "Religious institution"
    36 "Hawker"
    40 "PNFP/NGO"
    41 "PNFP/NGO hospital"
    42 "PNFP/NGO health facility"
    96 "Other"
    98 "Don't know"
;
label define SH128AA 
     0 "No"
     1 "Yes"
;
label define SH128AB 
     0 "No"
     1 "Yes"
;
label define SH128AC 
     0 "No"
     1 "Yes"
;
label define SH128AD 
     0 "No"
     1 "Yes"
;
label define SH128AE 
     0 "No"
     1 "Yes"
;
label define SH128AF 
     0 "No"
     1 "Yes"
;
label define SH128AG 
     0 "No"
     1 "Yes"
;
label define SH128AH 
     0 "No"
     1 "Yes"
;
label define SH128AI 
     0 "No"
     1 "Yes"
;
label define SH128AJ 
     0 "No"
     1 "Yes"
;
label define SH128AK 
     0 "No"
     1 "Yes"
;
label define SH128AX 
     0 "No"
     1 "Yes"
;
label define SH128AZ 
     0 "No"
     1 "Yes"
;
label define HML12   
     0 "Did not sleep under a net"
     1 "Only treated (ITN) nets"
     2 "Both treated (ITN) and untreated nets"
     3 "Only untreated nets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    97 "97+"
    98 "Don't know"
;
label define HML17   
     0 "No data from Individual file"
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HML20   
     0 "No"
     1 "Yes"
;
label define HML30   
     0 "Not in household"
;
label define HML31   
     1 "Granted"
     2 "Parent/other responsible refused"
     3 "Respondent refused"
     4 "Adult/parent not present"
     5 "Minor not present"
;
label define HML32   
     0 "Negative"
     1 "Positive"
     6 "Test undetermined"
     7 "Sample not found in lab database"
;
label define HML32A  
     0 "No"
     1 "Yes"
;
label define HML32B  
     0 "No"
     1 "Yes"
;
label define HML32C  
     0 "No"
     1 "Yes"
;
label define HML32D  
     0 "No"
     1 "Yes"
;
label define HML32E  
     0 "No"
     1 "Yes"
;
label define HML32F  
     0 "No"
     1 "Yes"
;
label define HML32G  
     0 "No"
     1 "Yes"
;
label define HML33   
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HML35   
     0 "Negative"
     1 "Positive"
;

#delimit cr
label values hv003    HV003   
label values hv015    HV015   
label values hv020    HV020   
label values hv022    HV022   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv045a   HV045A  
label values hv045b   HV045B  
label values hv045c   HV045C  
label values hv046    HV046   
label values hv803    HV803   
label values hv201    HV201   
label values hv202    HV202   
label values hv201a   HV201A  
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv235    HV235   
label values hv238    HV238   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv243e   HV243E  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246b   HV246B  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv246h   HV246H  
label values hv246i   HV246I  
label values hv246j   HV246J  
label values hv246k   HV246K  
label values hv247    HV247   
label values hv253    HV253   
label values hv253a   HV253A  
label values hv253b   HV253B  
label values hv253c   HV253C  
label values hv253d   HV253D  
label values hv253e   HV253E  
label values hv253f   HV253F  
label values hv253g   HV253G  
label values hv253h   HV253H  
label values hv253x   HV253X  
label values hv253z   HV253Z  
label values hv270    HV270   
label values hv270a   HV270A  
label values hml1     HML1    
label values shdistrict SHDISTRICT
label values shrefugee SHREFUGEE
label values sh114g   SH114G  
label values sh114h   SH114H  
label values sh114i   SH114I  
label values sh114j   SH114J  
label values sh114k   SH114K  
label values sh114l   SH114L  
label values sh114m   SH114M  
label values sh115h   SH115H  
label values sh117a   SH117A  
label values sh117c   SH117C  
label values sh118    SH118   
label values sh118a   SH118A  
label values hv101_01 HV101   
label values hv101_02 HV101   
label values hv101_03 HV101   
label values hv101_04 HV101   
label values hv101_05 HV101   
label values hv101_06 HV101   
label values hv101_07 HV101   
label values hv101_08 HV101   
label values hv101_09 HV101   
label values hv101_10 HV101   
label values hv101_11 HV101   
label values hv101_12 HV101   
label values hv101_13 HV101   
label values hv101_14 HV101   
label values hv101_15 HV101   
label values hv101_16 HV101   
label values hv101_17 HV101   
label values hv101_18 HV101   
label values hv101_19 HV101   
label values hv101_20 HV101   
label values hv101_21 HV101   
label values hv101_22 HV101   
label values hv101_23 HV101   
label values hv101_24 HV101   
label values hv101_25 HV101   
label values hv101_26 HV101   
label values hv101_27 HV101   
label values hv101_28 HV101   
label values hv101_29 HV101   
label values hv101_30 HV101   
label values hv101_31 HV101   
label values hv101_32 HV101   
label values hv101_33 HV101   
label values hv101_34 HV101   
label values hv101_35 HV101   
label values hv101_36 HV101   
label values hv102_01 HV102   
label values hv102_02 HV102   
label values hv102_03 HV102   
label values hv102_04 HV102   
label values hv102_05 HV102   
label values hv102_06 HV102   
label values hv102_07 HV102   
label values hv102_08 HV102   
label values hv102_09 HV102   
label values hv102_10 HV102   
label values hv102_11 HV102   
label values hv102_12 HV102   
label values hv102_13 HV102   
label values hv102_14 HV102   
label values hv102_15 HV102   
label values hv102_16 HV102   
label values hv102_17 HV102   
label values hv102_18 HV102   
label values hv102_19 HV102   
label values hv102_20 HV102   
label values hv102_21 HV102   
label values hv102_22 HV102   
label values hv102_23 HV102   
label values hv102_24 HV102   
label values hv102_25 HV102   
label values hv102_26 HV102   
label values hv102_27 HV102   
label values hv102_28 HV102   
label values hv102_29 HV102   
label values hv102_30 HV102   
label values hv102_31 HV102   
label values hv102_32 HV102   
label values hv102_33 HV102   
label values hv102_34 HV102   
label values hv102_35 HV102   
label values hv102_36 HV102   
label values hv103_01 HV103   
label values hv103_02 HV103   
label values hv103_03 HV103   
label values hv103_04 HV103   
label values hv103_05 HV103   
label values hv103_06 HV103   
label values hv103_07 HV103   
label values hv103_08 HV103   
label values hv103_09 HV103   
label values hv103_10 HV103   
label values hv103_11 HV103   
label values hv103_12 HV103   
label values hv103_13 HV103   
label values hv103_14 HV103   
label values hv103_15 HV103   
label values hv103_16 HV103   
label values hv103_17 HV103   
label values hv103_18 HV103   
label values hv103_19 HV103   
label values hv103_20 HV103   
label values hv103_21 HV103   
label values hv103_22 HV103   
label values hv103_23 HV103   
label values hv103_24 HV103   
label values hv103_25 HV103   
label values hv103_26 HV103   
label values hv103_27 HV103   
label values hv103_28 HV103   
label values hv103_29 HV103   
label values hv103_30 HV103   
label values hv103_31 HV103   
label values hv103_32 HV103   
label values hv103_33 HV103   
label values hv103_34 HV103   
label values hv103_35 HV103   
label values hv103_36 HV103   
label values hv104_01 HV104   
label values hv104_02 HV104   
label values hv104_03 HV104   
label values hv104_04 HV104   
label values hv104_05 HV104   
label values hv104_06 HV104   
label values hv104_07 HV104   
label values hv104_08 HV104   
label values hv104_09 HV104   
label values hv104_10 HV104   
label values hv104_11 HV104   
label values hv104_12 HV104   
label values hv104_13 HV104   
label values hv104_14 HV104   
label values hv104_15 HV104   
label values hv104_16 HV104   
label values hv104_17 HV104   
label values hv104_18 HV104   
label values hv104_19 HV104   
label values hv104_20 HV104   
label values hv104_21 HV104   
label values hv104_22 HV104   
label values hv104_23 HV104   
label values hv104_24 HV104   
label values hv104_25 HV104   
label values hv104_26 HV104   
label values hv104_27 HV104   
label values hv104_28 HV104   
label values hv104_29 HV104   
label values hv104_30 HV104   
label values hv104_31 HV104   
label values hv104_32 HV104   
label values hv104_33 HV104   
label values hv104_34 HV104   
label values hv104_35 HV104   
label values hv104_36 HV104   
label values hv105_01 HV105   
label values hv105_02 HV105   
label values hv105_03 HV105   
label values hv105_04 HV105   
label values hv105_05 HV105   
label values hv105_06 HV105   
label values hv105_07 HV105   
label values hv105_08 HV105   
label values hv105_09 HV105   
label values hv105_10 HV105   
label values hv105_11 HV105   
label values hv105_12 HV105   
label values hv105_13 HV105   
label values hv105_14 HV105   
label values hv105_15 HV105   
label values hv105_16 HV105   
label values hv105_17 HV105   
label values hv105_18 HV105   
label values hv105_19 HV105   
label values hv105_20 HV105   
label values hv105_21 HV105   
label values hv105_22 HV105   
label values hv105_23 HV105   
label values hv105_24 HV105   
label values hv105_25 HV105   
label values hv105_26 HV105   
label values hv105_27 HV105   
label values hv105_28 HV105   
label values hv105_29 HV105   
label values hv105_30 HV105   
label values hv105_31 HV105   
label values hv105_32 HV105   
label values hv105_33 HV105   
label values hv105_34 HV105   
label values hv105_35 HV105   
label values hv105_36 HV105   
label values hv117_01 HV117   
label values hv117_02 HV117   
label values hv117_03 HV117   
label values hv117_04 HV117   
label values hv117_05 HV117   
label values hv117_06 HV117   
label values hv117_07 HV117   
label values hv117_08 HV117   
label values hv117_09 HV117   
label values hv117_10 HV117   
label values hv117_11 HV117   
label values hv117_12 HV117   
label values hv117_13 HV117   
label values hv117_14 HV117   
label values hv117_15 HV117   
label values hv117_16 HV117   
label values hv117_17 HV117   
label values hv117_18 HV117   
label values hv117_19 HV117   
label values hv117_20 HV117   
label values hv117_21 HV117   
label values hv117_22 HV117   
label values hv117_23 HV117   
label values hv117_24 HV117   
label values hv117_25 HV117   
label values hv117_26 HV117   
label values hv117_27 HV117   
label values hv117_28 HV117   
label values hv117_29 HV117   
label values hv117_30 HV117   
label values hv117_31 HV117   
label values hv117_32 HV117   
label values hv117_33 HV117   
label values hv117_34 HV117   
label values hv117_35 HV117   
label values hv117_36 HV117   
label values hv120_01 HV120   
label values hv120_02 HV120   
label values hv120_03 HV120   
label values hv120_04 HV120   
label values hv120_05 HV120   
label values hv120_06 HV120   
label values hv120_07 HV120   
label values hv120_08 HV120   
label values hv120_09 HV120   
label values hv120_10 HV120   
label values hv120_11 HV120   
label values hv120_12 HV120   
label values hv120_13 HV120   
label values hv120_14 HV120   
label values hv120_15 HV120   
label values hv120_16 HV120   
label values hv120_17 HV120   
label values hv120_18 HV120   
label values hv120_19 HV120   
label values hv120_20 HV120   
label values hv120_21 HV120   
label values hv120_22 HV120   
label values hv120_23 HV120   
label values hv120_24 HV120   
label values hv120_25 HV120   
label values hv120_26 HV120   
label values hv120_27 HV120   
label values hv120_28 HV120   
label values hv120_29 HV120   
label values hv120_30 HV120   
label values hv120_31 HV120   
label values hv120_32 HV120   
label values hv120_33 HV120   
label values hv120_34 HV120   
label values hv120_35 HV120   
label values hv120_36 HV120   
label values hc16_1   HC16    
label values hc16_2   HC16    
label values hc16_3   HC16    
label values hc16_4   HC16    
label values hc16_5   HC16    
label values hc16_6   HC16    
label values hc16_7   HC16    
label values hc27_1   HC27    
label values hc27_2   HC27    
label values hc27_3   HC27    
label values hc27_4   HC27    
label values hc27_5   HC27    
label values hc27_6   HC27    
label values hc27_7   HC27    
label values hc30_1   HC30    
label values hc30_2   HC30    
label values hc30_3   HC30    
label values hc30_4   HC30    
label values hc30_5   HC30    
label values hc30_6   HC30    
label values hc30_7   HC30    
label values hc31_1   HC31    
label values hc31_2   HC31    
label values hc31_3   HC31    
label values hc31_4   HC31    
label values hc31_5   HC31    
label values hc31_6   HC31    
label values hc31_7   HC31    
label values hc33_1   HC33    
label values hc33_2   HC33    
label values hc33_3   HC33    
label values hc33_4   HC33    
label values hc33_5   HC33    
label values hc33_6   HC33    
label values hc33_7   HC33    
label values hc51_1   HC51    
label values hc51_2   HC51    
label values hc51_3   HC51    
label values hc51_4   HC51    
label values hc51_5   HC51    
label values hc51_6   HC51    
label values hc51_7   HC51    
label values hc52_1   HC52    
label values hc52_2   HC52    
label values hc52_3   HC52    
label values hc52_4   HC52    
label values hc52_5   HC52    
label values hc52_6   HC52    
label values hc52_7   HC52    
label values hc53_1   HC53    
label values hc53_2   HC53    
label values hc53_3   HC53    
label values hc53_4   HC53    
label values hc53_5   HC53    
label values hc53_6   HC53    
label values hc53_7   HC53    
label values hc55_1   HC55    
label values hc55_2   HC55    
label values hc55_3   HC55    
label values hc55_4   HC55    
label values hc55_5   HC55    
label values hc55_6   HC55    
label values hc55_7   HC55    
label values hc56_1   HC56    
label values hc56_2   HC56    
label values hc56_3   HC56    
label values hc56_4   HC56    
label values hc56_5   HC56    
label values hc56_6   HC56    
label values hc56_7   HC56    
label values hc57_1   HC57    
label values hc57_2   HC57    
label values hc57_3   HC57    
label values hc57_4   HC57    
label values hc57_5   HC57    
label values hc57_6   HC57    
label values hc57_7   HC57    
label values hc58_1   HC58    
label values hc58_2   HC58    
label values hc58_3   HC58    
label values hc58_4   HC58    
label values hc58_5   HC58    
label values hc58_6   HC58    
label values hc58_7   HC58    
label values hc60_1   HC60    
label values hc60_2   HC60    
label values hc60_3   HC60    
label values hc60_4   HC60    
label values hc60_5   HC60    
label values hc60_6   HC60    
label values hc60_7   HC60    
label values hc61_1   HC61    
label values hc61_2   HC61    
label values hc61_3   HC61    
label values hc61_4   HC61    
label values hc61_5   HC61    
label values hc61_6   HC61    
label values hc61_7   HC61    
label values hc62_1   HC62    
label values hc62_2   HC62    
label values hc62_3   HC62    
label values hc62_4   HC62    
label values hc62_5   HC62    
label values hc62_6   HC62    
label values hc62_7   HC62    
label values hc68_1   HC68    
label values hc68_2   HC68    
label values hc68_3   HC68    
label values hc68_4   HC68    
label values hc68_5   HC68    
label values hc68_6   HC68    
label values hc68_7   HC68    
label values hc70_1   HC70    
label values hc70_2   HC70    
label values hc70_3   HC70    
label values hc70_4   HC70    
label values hc70_5   HC70    
label values hc70_6   HC70    
label values hc70_7   HC70    
label values hc71_1   HC71    
label values hc71_2   HC71    
label values hc71_3   HC71    
label values hc71_4   HC71    
label values hc71_5   HC71    
label values hc71_6   HC71    
label values hc71_7   HC71    
label values hc72_1   HC72    
label values hc72_2   HC72    
label values hc72_3   HC72    
label values hc72_4   HC72    
label values hc72_5   HC72    
label values hc72_6   HC72    
label values hc72_7   HC72    
label values hc73_1   HC73    
label values hc73_2   HC73    
label values hc73_3   HC73    
label values hc73_4   HC73    
label values hc73_5   HC73    
label values hc73_6   HC73    
label values hc73_7   HC73    
label values sb118a_1 SB118A  
label values sb118a_2 SB118A  
label values sb118a_3 SB118A  
label values sb118a_4 SB118A  
label values sb118a_5 SB118A  
label values sb118a_6 SB118A  
label values sb118a_7 SB118A  
label values sb118b_1 SB118B  
label values sb118b_2 SB118B  
label values sb118b_3 SB118B  
label values sb118b_4 SB118B  
label values sb118b_5 SB118B  
label values sb118b_6 SB118B  
label values sb118b_7 SB118B  
label values sb118c_1 SB118C  
label values sb118c_2 SB118C  
label values sb118c_3 SB118C  
label values sb118c_4 SB118C  
label values sb118c_5 SB118C  
label values sb118c_6 SB118C  
label values sb118c_7 SB118C  
label values sb118d_1 SB118D  
label values sb118d_2 SB118D  
label values sb118d_3 SB118D  
label values sb118d_4 SB118D  
label values sb118d_5 SB118D  
label values sb118d_6 SB118D  
label values sb118d_7 SB118D  
label values sb118e_1 SB118E  
label values sb118e_2 SB118E  
label values sb118e_3 SB118E  
label values sb118e_4 SB118E  
label values sb118e_5 SB118E  
label values sb118e_6 SB118E  
label values sb118e_7 SB118E  
label values sb118f_1 SB118F  
label values sb118f_2 SB118F  
label values sb118f_3 SB118F  
label values sb118f_4 SB118F  
label values sb118f_5 SB118F  
label values sb118f_6 SB118F  
label values sb118f_7 SB118F  
label values sb118g_1 SB118G  
label values sb118g_2 SB118G  
label values sb118g_3 SB118G  
label values sb118g_4 SB118G  
label values sb118g_5 SB118G  
label values sb118g_6 SB118G  
label values sb118g_7 SB118G  
label values sb118h_1 SB118H  
label values sb118h_2 SB118H  
label values sb118h_3 SB118H  
label values sb118h_4 SB118H  
label values sb118h_5 SB118H  
label values sb118h_6 SB118H  
label values sb118h_7 SB118H  
label values sb121_1  SB121   
label values sb121_2  SB121   
label values sb121_3  SB121   
label values sb121_4  SB121   
label values sb121_5  SB121   
label values sb121_6  SB121   
label values sb121_7  SB121   
label values sb125_1  SB125   
label values sb125_2  SB125   
label values sb125_3  SB125   
label values sb125_4  SB125   
label values sb125_5  SB125   
label values sb125_6  SB125   
label values sb125_7  SB125   
label values hml3_1   HML3    
label values hml3_2   HML3    
label values hml3_3   HML3    
label values hml3_4   HML3    
label values hml3_5   HML3    
label values hml3_6   HML3    
label values hml3_7   HML3    
label values hml4_1   HML4    
label values hml4_2   HML4    
label values hml4_3   HML4    
label values hml4_4   HML4    
label values hml4_5   HML4    
label values hml4_6   HML4    
label values hml4_7   HML4    
label values hml5_1   HML5    
label values hml5_2   HML5    
label values hml5_3   HML5    
label values hml5_4   HML5    
label values hml5_5   HML5    
label values hml5_6   HML5    
label values hml5_7   HML5    
label values hml6_1   HML6    
label values hml6_2   HML6    
label values hml6_3   HML6    
label values hml6_4   HML6    
label values hml6_5   HML6    
label values hml6_6   HML6    
label values hml6_7   HML6    
label values hml7_1   HML7    
label values hml7_2   HML7    
label values hml7_3   HML7    
label values hml7_4   HML7    
label values hml7_5   HML7    
label values hml7_6   HML7    
label values hml7_7   HML7    
label values hml8_1   HML8    
label values hml8_2   HML8    
label values hml8_3   HML8    
label values hml8_4   HML8    
label values hml8_5   HML8    
label values hml8_6   HML8    
label values hml8_7   HML8    
label values hml9_1   HML9    
label values hml9_2   HML9    
label values hml9_3   HML9    
label values hml9_4   HML9    
label values hml9_5   HML9    
label values hml9_6   HML9    
label values hml9_7   HML9    
label values hml10_1  HML10   
label values hml10_2  HML10   
label values hml10_3  HML10   
label values hml10_4  HML10   
label values hml10_5  HML10   
label values hml10_6  HML10   
label values hml10_7  HML10   
label values hml11_1  HML11   
label values hml11_2  HML11   
label values hml11_3  HML11   
label values hml11_4  HML11   
label values hml11_5  HML11   
label values hml11_6  HML11   
label values hml11_7  HML11   
label values hml21_1  HML21   
label values hml21_2  HML21   
label values hml21_3  HML21   
label values hml21_4  HML21   
label values hml21_5  HML21   
label values hml21_6  HML21   
label values hml21_7  HML21   
label values hmla_1   HMLA    
label values hmla_2   HMLA    
label values hmla_3   HMLA    
label values hmla_4   HMLA    
label values hmla_5   HMLA    
label values hmla_6   HMLA    
label values hmla_7   HMLA    
label values hml22_1  HML22   
label values hml22_2  HML22   
label values hml22_3  HML22   
label values hml22_4  HML22   
label values hml22_5  HML22   
label values hml22_6  HML22   
label values hml22_7  HML22   
label values hml23_1  HML23   
label values hml23_2  HML23   
label values hml23_3  HML23   
label values hml23_4  HML23   
label values hml23_5  HML23   
label values hml23_6  HML23   
label values hml23_7  HML23   
label values sh128aa_1 SH128AA 
label values sh128aa_2 SH128AA 
label values sh128aa_3 SH128AA 
label values sh128aa_4 SH128AA 
label values sh128aa_5 SH128AA 
label values sh128aa_6 SH128AA 
label values sh128aa_7 SH128AA 
label values sh128ab_1 SH128AB 
label values sh128ab_2 SH128AB 
label values sh128ab_3 SH128AB 
label values sh128ab_4 SH128AB 
label values sh128ab_5 SH128AB 
label values sh128ab_6 SH128AB 
label values sh128ab_7 SH128AB 
label values sh128ac_1 SH128AC 
label values sh128ac_2 SH128AC 
label values sh128ac_3 SH128AC 
label values sh128ac_4 SH128AC 
label values sh128ac_5 SH128AC 
label values sh128ac_6 SH128AC 
label values sh128ac_7 SH128AC 
label values sh128ad_1 SH128AD 
label values sh128ad_2 SH128AD 
label values sh128ad_3 SH128AD 
label values sh128ad_4 SH128AD 
label values sh128ad_5 SH128AD 
label values sh128ad_6 SH128AD 
label values sh128ad_7 SH128AD 
label values sh128ae_1 SH128AE 
label values sh128ae_2 SH128AE 
label values sh128ae_3 SH128AE 
label values sh128ae_4 SH128AE 
label values sh128ae_5 SH128AE 
label values sh128ae_6 SH128AE 
label values sh128ae_7 SH128AE 
label values sh128af_1 SH128AF 
label values sh128af_2 SH128AF 
label values sh128af_3 SH128AF 
label values sh128af_4 SH128AF 
label values sh128af_5 SH128AF 
label values sh128af_6 SH128AF 
label values sh128af_7 SH128AF 
label values sh128ag_1 SH128AG 
label values sh128ag_2 SH128AG 
label values sh128ag_3 SH128AG 
label values sh128ag_4 SH128AG 
label values sh128ag_5 SH128AG 
label values sh128ag_6 SH128AG 
label values sh128ag_7 SH128AG 
label values sh128ah_1 SH128AH 
label values sh128ah_2 SH128AH 
label values sh128ah_3 SH128AH 
label values sh128ah_4 SH128AH 
label values sh128ah_5 SH128AH 
label values sh128ah_6 SH128AH 
label values sh128ah_7 SH128AH 
label values sh128ai_1 SH128AI 
label values sh128ai_2 SH128AI 
label values sh128ai_3 SH128AI 
label values sh128ai_4 SH128AI 
label values sh128ai_5 SH128AI 
label values sh128ai_6 SH128AI 
label values sh128ai_7 SH128AI 
label values sh128aj_1 SH128AJ 
label values sh128aj_2 SH128AJ 
label values sh128aj_3 SH128AJ 
label values sh128aj_4 SH128AJ 
label values sh128aj_5 SH128AJ 
label values sh128aj_6 SH128AJ 
label values sh128aj_7 SH128AJ 
label values sh128ak_1 SH128AK 
label values sh128ak_2 SH128AK 
label values sh128ak_3 SH128AK 
label values sh128ak_4 SH128AK 
label values sh128ak_5 SH128AK 
label values sh128ak_6 SH128AK 
label values sh128ak_7 SH128AK 
label values sh128ax_1 SH128AX 
label values sh128ax_2 SH128AX 
label values sh128ax_3 SH128AX 
label values sh128ax_4 SH128AX 
label values sh128ax_5 SH128AX 
label values sh128ax_6 SH128AX 
label values sh128ax_7 SH128AX 
label values sh128az_1 SH128AZ 
label values sh128az_2 SH128AZ 
label values sh128az_3 SH128AZ 
label values sh128az_4 SH128AZ 
label values sh128az_5 SH128AZ 
label values sh128az_6 SH128AZ 
label values sh128az_7 SH128AZ 
label values hml12_01 HML12   
label values hml12_02 HML12   
label values hml12_03 HML12   
label values hml12_04 HML12   
label values hml12_05 HML12   
label values hml12_06 HML12   
label values hml12_07 HML12   
label values hml12_08 HML12   
label values hml12_09 HML12   
label values hml12_10 HML12   
label values hml12_11 HML12   
label values hml12_12 HML12   
label values hml12_13 HML12   
label values hml12_14 HML12   
label values hml12_15 HML12   
label values hml12_16 HML12   
label values hml12_17 HML12   
label values hml12_18 HML12   
label values hml12_19 HML12   
label values hml12_20 HML12   
label values hml12_21 HML12   
label values hml12_22 HML12   
label values hml12_23 HML12   
label values hml12_24 HML12   
label values hml12_25 HML12   
label values hml12_26 HML12   
label values hml12_27 HML12   
label values hml12_28 HML12   
label values hml12_29 HML12   
label values hml12_30 HML12   
label values hml12_31 HML12   
label values hml12_32 HML12   
label values hml12_33 HML12   
label values hml12_34 HML12   
label values hml12_35 HML12   
label values hml12_36 HML12   
label values hml13_01 HML13   
label values hml13_02 HML13   
label values hml13_03 HML13   
label values hml13_04 HML13   
label values hml13_05 HML13   
label values hml13_06 HML13   
label values hml13_07 HML13   
label values hml13_08 HML13   
label values hml13_09 HML13   
label values hml13_10 HML13   
label values hml13_11 HML13   
label values hml13_12 HML13   
label values hml13_13 HML13   
label values hml13_14 HML13   
label values hml13_15 HML13   
label values hml13_16 HML13   
label values hml13_17 HML13   
label values hml13_18 HML13   
label values hml13_19 HML13   
label values hml13_20 HML13   
label values hml13_21 HML13   
label values hml13_22 HML13   
label values hml13_23 HML13   
label values hml13_24 HML13   
label values hml13_25 HML13   
label values hml13_26 HML13   
label values hml13_27 HML13   
label values hml13_28 HML13   
label values hml13_29 HML13   
label values hml13_30 HML13   
label values hml13_31 HML13   
label values hml13_32 HML13   
label values hml13_33 HML13   
label values hml13_34 HML13   
label values hml13_35 HML13   
label values hml13_36 HML13   
label values hml16_01 HML16   
label values hml16_02 HML16   
label values hml16_03 HML16   
label values hml16_04 HML16   
label values hml16_05 HML16   
label values hml16_06 HML16   
label values hml16_07 HML16   
label values hml16_08 HML16   
label values hml16_09 HML16   
label values hml16_10 HML16   
label values hml16_11 HML16   
label values hml16_12 HML16   
label values hml16_13 HML16   
label values hml16_14 HML16   
label values hml16_15 HML16   
label values hml16_16 HML16   
label values hml16_17 HML16   
label values hml16_18 HML16   
label values hml16_19 HML16   
label values hml16_20 HML16   
label values hml16_21 HML16   
label values hml16_22 HML16   
label values hml16_23 HML16   
label values hml16_24 HML16   
label values hml16_25 HML16   
label values hml16_26 HML16   
label values hml16_27 HML16   
label values hml16_28 HML16   
label values hml16_29 HML16   
label values hml16_30 HML16   
label values hml16_31 HML16   
label values hml16_32 HML16   
label values hml16_33 HML16   
label values hml16_34 HML16   
label values hml16_35 HML16   
label values hml16_36 HML16   
label values hml17_01 HML17   
label values hml17_02 HML17   
label values hml17_03 HML17   
label values hml17_04 HML17   
label values hml17_05 HML17   
label values hml17_06 HML17   
label values hml17_07 HML17   
label values hml17_08 HML17   
label values hml17_09 HML17   
label values hml17_10 HML17   
label values hml17_11 HML17   
label values hml17_12 HML17   
label values hml17_13 HML17   
label values hml17_14 HML17   
label values hml17_15 HML17   
label values hml17_16 HML17   
label values hml17_17 HML17   
label values hml17_18 HML17   
label values hml17_19 HML17   
label values hml17_20 HML17   
label values hml17_21 HML17   
label values hml17_22 HML17   
label values hml17_23 HML17   
label values hml17_24 HML17   
label values hml17_25 HML17   
label values hml17_26 HML17   
label values hml17_27 HML17   
label values hml17_28 HML17   
label values hml17_29 HML17   
label values hml17_30 HML17   
label values hml17_31 HML17   
label values hml17_32 HML17   
label values hml17_33 HML17   
label values hml17_34 HML17   
label values hml17_35 HML17   
label values hml17_36 HML17   
label values hml18_01 HML18   
label values hml18_02 HML18   
label values hml18_03 HML18   
label values hml18_04 HML18   
label values hml18_05 HML18   
label values hml18_06 HML18   
label values hml18_07 HML18   
label values hml18_08 HML18   
label values hml18_09 HML18   
label values hml18_10 HML18   
label values hml18_11 HML18   
label values hml18_12 HML18   
label values hml18_13 HML18   
label values hml18_14 HML18   
label values hml18_15 HML18   
label values hml18_16 HML18   
label values hml18_17 HML18   
label values hml18_18 HML18   
label values hml18_19 HML18   
label values hml18_20 HML18   
label values hml18_21 HML18   
label values hml18_22 HML18   
label values hml18_23 HML18   
label values hml18_24 HML18   
label values hml18_25 HML18   
label values hml18_26 HML18   
label values hml18_27 HML18   
label values hml18_28 HML18   
label values hml18_29 HML18   
label values hml18_30 HML18   
label values hml18_31 HML18   
label values hml18_32 HML18   
label values hml18_33 HML18   
label values hml18_34 HML18   
label values hml18_35 HML18   
label values hml18_36 HML18   
label values hml19_01 HML19   
label values hml19_02 HML19   
label values hml19_03 HML19   
label values hml19_04 HML19   
label values hml19_05 HML19   
label values hml19_06 HML19   
label values hml19_07 HML19   
label values hml19_08 HML19   
label values hml19_09 HML19   
label values hml19_10 HML19   
label values hml19_11 HML19   
label values hml19_12 HML19   
label values hml19_13 HML19   
label values hml19_14 HML19   
label values hml19_15 HML19   
label values hml19_16 HML19   
label values hml19_17 HML19   
label values hml19_18 HML19   
label values hml19_19 HML19   
label values hml19_20 HML19   
label values hml19_21 HML19   
label values hml19_22 HML19   
label values hml19_23 HML19   
label values hml19_24 HML19   
label values hml19_25 HML19   
label values hml19_26 HML19   
label values hml19_27 HML19   
label values hml19_28 HML19   
label values hml19_29 HML19   
label values hml19_30 HML19   
label values hml19_31 HML19   
label values hml19_32 HML19   
label values hml19_33 HML19   
label values hml19_34 HML19   
label values hml19_35 HML19   
label values hml19_36 HML19   
label values hml20_01 HML20   
label values hml20_02 HML20   
label values hml20_03 HML20   
label values hml20_04 HML20   
label values hml20_05 HML20   
label values hml20_06 HML20   
label values hml20_07 HML20   
label values hml20_08 HML20   
label values hml20_09 HML20   
label values hml20_10 HML20   
label values hml20_11 HML20   
label values hml20_12 HML20   
label values hml20_13 HML20   
label values hml20_14 HML20   
label values hml20_15 HML20   
label values hml20_16 HML20   
label values hml20_17 HML20   
label values hml20_18 HML20   
label values hml20_19 HML20   
label values hml20_20 HML20   
label values hml20_21 HML20   
label values hml20_22 HML20   
label values hml20_23 HML20   
label values hml20_24 HML20   
label values hml20_25 HML20   
label values hml20_26 HML20   
label values hml20_27 HML20   
label values hml20_28 HML20   
label values hml20_29 HML20   
label values hml20_30 HML20   
label values hml20_31 HML20   
label values hml20_32 HML20   
label values hml20_33 HML20   
label values hml20_34 HML20   
label values hml20_35 HML20   
label values hml20_36 HML20   
label values hml30_01 HML30   
label values hml30_02 HML30   
label values hml30_03 HML30   
label values hml30_04 HML30   
label values hml30_05 HML30   
label values hml30_06 HML30   
label values hml30_07 HML30   
label values hml30_08 HML30   
label values hml30_09 HML30   
label values hml30_10 HML30   
label values hml30_11 HML30   
label values hml30_12 HML30   
label values hml30_13 HML30   
label values hml30_14 HML30   
label values hml30_15 HML30   
label values hml30_16 HML30   
label values hml30_17 HML30   
label values hml30_18 HML30   
label values hml30_19 HML30   
label values hml30_20 HML30   
label values hml30_21 HML30   
label values hml30_22 HML30   
label values hml30_23 HML30   
label values hml30_24 HML30   
label values hml30_25 HML30   
label values hml30_26 HML30   
label values hml30_27 HML30   
label values hml30_28 HML30   
label values hml30_29 HML30   
label values hml30_30 HML30   
label values hml30_31 HML30   
label values hml30_32 HML30   
label values hml30_33 HML30   
label values hml30_34 HML30   
label values hml30_35 HML30   
label values hml30_36 HML30   
label values hml31_01 HML31   
label values hml31_02 HML31   
label values hml31_03 HML31   
label values hml31_04 HML31   
label values hml31_05 HML31   
label values hml31_06 HML31   
label values hml31_07 HML31   
label values hml31_08 HML31   
label values hml31_09 HML31   
label values hml31_10 HML31   
label values hml31_11 HML31   
label values hml31_12 HML31   
label values hml31_13 HML31   
label values hml31_14 HML31   
label values hml31_15 HML31   
label values hml31_16 HML31   
label values hml31_17 HML31   
label values hml31_18 HML31   
label values hml31_19 HML31   
label values hml31_20 HML31   
label values hml31_21 HML31   
label values hml31_22 HML31   
label values hml31_23 HML31   
label values hml31_24 HML31   
label values hml31_25 HML31   
label values hml31_26 HML31   
label values hml31_27 HML31   
label values hml31_28 HML31   
label values hml31_29 HML31   
label values hml31_30 HML31   
label values hml31_31 HML31   
label values hml31_32 HML31   
label values hml31_33 HML31   
label values hml31_34 HML31   
label values hml31_35 HML31   
label values hml31_36 HML31   
label values hml32_01 HML32   
label values hml32_02 HML32   
label values hml32_03 HML32   
label values hml32_04 HML32   
label values hml32_05 HML32   
label values hml32_06 HML32   
label values hml32_07 HML32   
label values hml32_08 HML32   
label values hml32_09 HML32   
label values hml32_10 HML32   
label values hml32_11 HML32   
label values hml32_12 HML32   
label values hml32_13 HML32   
label values hml32_14 HML32   
label values hml32_15 HML32   
label values hml32_16 HML32   
label values hml32_17 HML32   
label values hml32_18 HML32   
label values hml32_19 HML32   
label values hml32_20 HML32   
label values hml32_21 HML32   
label values hml32_22 HML32   
label values hml32_23 HML32   
label values hml32_24 HML32   
label values hml32_25 HML32   
label values hml32_26 HML32   
label values hml32_27 HML32   
label values hml32_28 HML32   
label values hml32_29 HML32   
label values hml32_30 HML32   
label values hml32_31 HML32   
label values hml32_32 HML32   
label values hml32_33 HML32   
label values hml32_34 HML32   
label values hml32_35 HML32   
label values hml32_36 HML32   
label values hml32a_01 HML32A  
label values hml32a_02 HML32A  
label values hml32a_03 HML32A  
label values hml32a_04 HML32A  
label values hml32a_05 HML32A  
label values hml32a_06 HML32A  
label values hml32a_07 HML32A  
label values hml32a_08 HML32A  
label values hml32a_09 HML32A  
label values hml32a_10 HML32A  
label values hml32a_11 HML32A  
label values hml32a_12 HML32A  
label values hml32a_13 HML32A  
label values hml32a_14 HML32A  
label values hml32a_15 HML32A  
label values hml32a_16 HML32A  
label values hml32a_17 HML32A  
label values hml32a_18 HML32A  
label values hml32a_19 HML32A  
label values hml32a_20 HML32A  
label values hml32a_21 HML32A  
label values hml32a_22 HML32A  
label values hml32a_23 HML32A  
label values hml32a_24 HML32A  
label values hml32a_25 HML32A  
label values hml32a_26 HML32A  
label values hml32a_27 HML32A  
label values hml32a_28 HML32A  
label values hml32a_29 HML32A  
label values hml32a_30 HML32A  
label values hml32a_31 HML32A  
label values hml32a_32 HML32A  
label values hml32a_33 HML32A  
label values hml32a_34 HML32A  
label values hml32a_35 HML32A  
label values hml32a_36 HML32A  
label values hml32b_01 HML32B  
label values hml32b_02 HML32B  
label values hml32b_03 HML32B  
label values hml32b_04 HML32B  
label values hml32b_05 HML32B  
label values hml32b_06 HML32B  
label values hml32b_07 HML32B  
label values hml32b_08 HML32B  
label values hml32b_09 HML32B  
label values hml32b_10 HML32B  
label values hml32b_11 HML32B  
label values hml32b_12 HML32B  
label values hml32b_13 HML32B  
label values hml32b_14 HML32B  
label values hml32b_15 HML32B  
label values hml32b_16 HML32B  
label values hml32b_17 HML32B  
label values hml32b_18 HML32B  
label values hml32b_19 HML32B  
label values hml32b_20 HML32B  
label values hml32b_21 HML32B  
label values hml32b_22 HML32B  
label values hml32b_23 HML32B  
label values hml32b_24 HML32B  
label values hml32b_25 HML32B  
label values hml32b_26 HML32B  
label values hml32b_27 HML32B  
label values hml32b_28 HML32B  
label values hml32b_29 HML32B  
label values hml32b_30 HML32B  
label values hml32b_31 HML32B  
label values hml32b_32 HML32B  
label values hml32b_33 HML32B  
label values hml32b_34 HML32B  
label values hml32b_35 HML32B  
label values hml32b_36 HML32B  
label values hml32c_01 HML32C  
label values hml32c_02 HML32C  
label values hml32c_03 HML32C  
label values hml32c_04 HML32C  
label values hml32c_05 HML32C  
label values hml32c_06 HML32C  
label values hml32c_07 HML32C  
label values hml32c_08 HML32C  
label values hml32c_09 HML32C  
label values hml32c_10 HML32C  
label values hml32c_11 HML32C  
label values hml32c_12 HML32C  
label values hml32c_13 HML32C  
label values hml32c_14 HML32C  
label values hml32c_15 HML32C  
label values hml32c_16 HML32C  
label values hml32c_17 HML32C  
label values hml32c_18 HML32C  
label values hml32c_19 HML32C  
label values hml32c_20 HML32C  
label values hml32c_21 HML32C  
label values hml32c_22 HML32C  
label values hml32c_23 HML32C  
label values hml32c_24 HML32C  
label values hml32c_25 HML32C  
label values hml32c_26 HML32C  
label values hml32c_27 HML32C  
label values hml32c_28 HML32C  
label values hml32c_29 HML32C  
label values hml32c_30 HML32C  
label values hml32c_31 HML32C  
label values hml32c_32 HML32C  
label values hml32c_33 HML32C  
label values hml32c_34 HML32C  
label values hml32c_35 HML32C  
label values hml32c_36 HML32C  
label values hml32d_01 HML32D  
label values hml32d_02 HML32D  
label values hml32d_03 HML32D  
label values hml32d_04 HML32D  
label values hml32d_05 HML32D  
label values hml32d_06 HML32D  
label values hml32d_07 HML32D  
label values hml32d_08 HML32D  
label values hml32d_09 HML32D  
label values hml32d_10 HML32D  
label values hml32d_11 HML32D  
label values hml32d_12 HML32D  
label values hml32d_13 HML32D  
label values hml32d_14 HML32D  
label values hml32d_15 HML32D  
label values hml32d_16 HML32D  
label values hml32d_17 HML32D  
label values hml32d_18 HML32D  
label values hml32d_19 HML32D  
label values hml32d_20 HML32D  
label values hml32d_21 HML32D  
label values hml32d_22 HML32D  
label values hml32d_23 HML32D  
label values hml32d_24 HML32D  
label values hml32d_25 HML32D  
label values hml32d_26 HML32D  
label values hml32d_27 HML32D  
label values hml32d_28 HML32D  
label values hml32d_29 HML32D  
label values hml32d_30 HML32D  
label values hml32d_31 HML32D  
label values hml32d_32 HML32D  
label values hml32d_33 HML32D  
label values hml32d_34 HML32D  
label values hml32d_35 HML32D  
label values hml32d_36 HML32D  
label values hml32e_01 HML32E  
label values hml32e_02 HML32E  
label values hml32e_03 HML32E  
label values hml32e_04 HML32E  
label values hml32e_05 HML32E  
label values hml32e_06 HML32E  
label values hml32e_07 HML32E  
label values hml32e_08 HML32E  
label values hml32e_09 HML32E  
label values hml32e_10 HML32E  
label values hml32e_11 HML32E  
label values hml32e_12 HML32E  
label values hml32e_13 HML32E  
label values hml32e_14 HML32E  
label values hml32e_15 HML32E  
label values hml32e_16 HML32E  
label values hml32e_17 HML32E  
label values hml32e_18 HML32E  
label values hml32e_19 HML32E  
label values hml32e_20 HML32E  
label values hml32e_21 HML32E  
label values hml32e_22 HML32E  
label values hml32e_23 HML32E  
label values hml32e_24 HML32E  
label values hml32e_25 HML32E  
label values hml32e_26 HML32E  
label values hml32e_27 HML32E  
label values hml32e_28 HML32E  
label values hml32e_29 HML32E  
label values hml32e_30 HML32E  
label values hml32e_31 HML32E  
label values hml32e_32 HML32E  
label values hml32e_33 HML32E  
label values hml32e_34 HML32E  
label values hml32e_35 HML32E  
label values hml32e_36 HML32E  
label values hml32f_01 HML32F  
label values hml32f_02 HML32F  
label values hml32f_03 HML32F  
label values hml32f_04 HML32F  
label values hml32f_05 HML32F  
label values hml32f_06 HML32F  
label values hml32f_07 HML32F  
label values hml32f_08 HML32F  
label values hml32f_09 HML32F  
label values hml32f_10 HML32F  
label values hml32f_11 HML32F  
label values hml32f_12 HML32F  
label values hml32f_13 HML32F  
label values hml32f_14 HML32F  
label values hml32f_15 HML32F  
label values hml32f_16 HML32F  
label values hml32f_17 HML32F  
label values hml32f_18 HML32F  
label values hml32f_19 HML32F  
label values hml32f_20 HML32F  
label values hml32f_21 HML32F  
label values hml32f_22 HML32F  
label values hml32f_23 HML32F  
label values hml32f_24 HML32F  
label values hml32f_25 HML32F  
label values hml32f_26 HML32F  
label values hml32f_27 HML32F  
label values hml32f_28 HML32F  
label values hml32f_29 HML32F  
label values hml32f_30 HML32F  
label values hml32f_31 HML32F  
label values hml32f_32 HML32F  
label values hml32f_33 HML32F  
label values hml32f_34 HML32F  
label values hml32f_35 HML32F  
label values hml32f_36 HML32F  
label values hml32g_01 HML32G  
label values hml32g_02 HML32G  
label values hml32g_03 HML32G  
label values hml32g_04 HML32G  
label values hml32g_05 HML32G  
label values hml32g_06 HML32G  
label values hml32g_07 HML32G  
label values hml32g_08 HML32G  
label values hml32g_09 HML32G  
label values hml32g_10 HML32G  
label values hml32g_11 HML32G  
label values hml32g_12 HML32G  
label values hml32g_13 HML32G  
label values hml32g_14 HML32G  
label values hml32g_15 HML32G  
label values hml32g_16 HML32G  
label values hml32g_17 HML32G  
label values hml32g_18 HML32G  
label values hml32g_19 HML32G  
label values hml32g_20 HML32G  
label values hml32g_21 HML32G  
label values hml32g_22 HML32G  
label values hml32g_23 HML32G  
label values hml32g_24 HML32G  
label values hml32g_25 HML32G  
label values hml32g_26 HML32G  
label values hml32g_27 HML32G  
label values hml32g_28 HML32G  
label values hml32g_29 HML32G  
label values hml32g_30 HML32G  
label values hml32g_31 HML32G  
label values hml32g_32 HML32G  
label values hml32g_33 HML32G  
label values hml32g_34 HML32G  
label values hml32g_35 HML32G  
label values hml32g_36 HML32G  
label values hml33_01 HML33   
label values hml33_02 HML33   
label values hml33_03 HML33   
label values hml33_04 HML33   
label values hml33_05 HML33   
label values hml33_06 HML33   
label values hml33_07 HML33   
label values hml33_08 HML33   
label values hml33_09 HML33   
label values hml33_10 HML33   
label values hml33_11 HML33   
label values hml33_12 HML33   
label values hml33_13 HML33   
label values hml33_14 HML33   
label values hml33_15 HML33   
label values hml33_16 HML33   
label values hml33_17 HML33   
label values hml33_18 HML33   
label values hml33_19 HML33   
label values hml33_20 HML33   
label values hml33_21 HML33   
label values hml33_22 HML33   
label values hml33_23 HML33   
label values hml33_24 HML33   
label values hml33_25 HML33   
label values hml33_26 HML33   
label values hml33_27 HML33   
label values hml33_28 HML33   
label values hml33_29 HML33   
label values hml33_30 HML33   
label values hml33_31 HML33   
label values hml33_32 HML33   
label values hml33_33 HML33   
label values hml33_34 HML33   
label values hml33_35 HML33   
label values hml33_36 HML33   
label values hml35_01 HML35   
label values hml35_02 HML35   
label values hml35_03 HML35   
label values hml35_04 HML35   
label values hml35_05 HML35   
label values hml35_06 HML35   
label values hml35_07 HML35   
label values hml35_08 HML35   
label values hml35_09 HML35   
label values hml35_10 HML35   
label values hml35_11 HML35   
label values hml35_12 HML35   
label values hml35_13 HML35   
label values hml35_14 HML35   
label values hml35_15 HML35   
label values hml35_16 HML35   
label values hml35_17 HML35   
label values hml35_18 HML35   
label values hml35_19 HML35   
label values hml35_20 HML35   
label values hml35_21 HML35   
label values hml35_22 HML35   
label values hml35_23 HML35   
label values hml35_24 HML35   
label values hml35_25 HML35   
label values hml35_26 HML35   
label values hml35_27 HML35   
label values hml35_28 HML35   
label values hml35_29 HML35   
label values hml35_30 HML35   
label values hml35_31 HML35   
label values hml35_32 HML35   
label values hml35_33 HML35   
label values hml35_34 HML35   
label values hml35_35 HML35   
label values hml35_36 HML35   
